
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#ifndef HPM_CLOCK_H
#define HPM_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

void init_board_clock(void);
void init_board_clock_source(void);
void init_uart0_clock(void);
void init_uart1_clock(void);
void init_uart2_clock(void);
void init_uart3_clock(void);
void init_i2c0_clock(void);
void init_i2c1_clock(void);
void init_i2c2_clock(void);
void init_i2c3_clock(void);
void init_spi1_clock(void);
void init_adc0_bus_clock(void);
void init_adc0_analog_clock(void);
void init_adc1_bus_clock(void);
void init_adc1_analog_clock(void);
void init_dac0_ahb_clock(void);
void init_dac0_analog_clock(void);
void init_dac1_ahb_clock(void);
void init_dac1_analog_clock(void);
void init_can0_clock(void);
void init_can1_clock(void);
void init_can2_clock(void);
void init_can3_clock(void);
void init_gptmr0_clock(void);
void init_gptmr1_clock(void);
void init_gptmr2_clock(void);
void init_gptmr3_clock(void);
void init_ptmr_clock(void);
void init_usb0_clock(void);
void init_acmp0_clock(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_CLOCK_H */
