
/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_py_pins_as_pgpio(void);
void init_uart0_pins(void);
void init_uart2_pins(void);
void init_uart3_pins(void);
void init_lin_transceiver_ctrl_pin(void);
void init_uart3_pin_as_gpio(void);
void init_i2c0_pins(void);
void init_i2c1_pins(void);
void init_gpio_pins(void);
void init_spi1_pins(void);
void init_spi1_pins_with_gpio_as_cs(void);
void init_gptmr0_pins(void);
void init_butn_pins(void);
void init_acmp_pins(void);
void init_pwm0_pins(void);
void init_adc_pins(void);
void init_adc_bldc_pins(void);
void init_adc_qeiv2_pins(void);
void init_usb0_pins(void);
void init_mcan3_pins(void);
void init_led_pins_as_gpio(void);
void init_led_pins_as_pwm(void);
void init_dac0_pins(void);
void init_dac1_pins(void);
void init_plb_pulse_pins(void);
void init_plb_filter_pins(void);
void init_qeo0_pins(void);
void init_sei_ctrl1_pins(void);
void init_rdc_pin_without_param(void);
void init_rdc_pin_for_sample_test(void);
void init_qeiv2_qei1_uvw_pins(void);
void init_qeiv2_qei1_ab_pins(void);
void init_qeiv2_qei1_abz_pins(void);
void init_opamp_pins(void);
void init_uart_break_signal_pin(void);
void init_gptmr0_channel0_pin_as_output(void);
void init_gptmr0_channel1_pin_as_output(void);
void init_gptmr0_channel3_pin_as_output(void);
void init_gptmr0_channel0_pin_as_capture(void);
void init_clk_ref_pin(void);
void init_brownout_indicate_pin(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
