excluded_targets:
  - debug
  - flash_uf2
  - flash_sdram_uf2
  - flash_xip
  - flash_xip_release
  - flash_sdram_xip
  - flash_sdram_xip_release
  - sec_core_img
  - sec_core_img_release
dependency:
  - lcd
