/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#ifndef HPM_SOC_IP_FEATURE_H
#define HPM_SOC_IP_FEATURE_H

/* PLIC related feature */
#define HPM_IP_FEATURE_PLIC_HIGHEST_PRIORITY 31
#define HPM_IP_FEATURE_PLIC_SUPPORT_S_MODE 1
#define HPM_IP_FEATURE_PLIC_HAS_TRIGGER_TYPE 1

/* UART related feature */
#define HPM_IP_FEATURE_UART_RX_IDLE_DETECT 1
#define HPM_IP_FEATURE_UART_FCRR 1
#define HPM_IP_FEATURE_UART_RX_EN 1
#define HPM_IP_FEATURE_UART_E00018_FIX 1
#define HPM_IP_FEATURE_UART_9BIT_MODE 1
#define HPM_IP_FEATURE_UART_TX_IDLE_DETECT 1
#define HPM_IP_FEATURE_UART_ADDR_MATCH 1
#define HPM_IP_FEATURE_UART_TRIG_MODE 1
#define HPM_IP_FEATURE_UART_FINE_FIFO_THRLD 1
#define HPM_IP_FEATURE_UART_IIR2 1
#define HPM_IP_FEATURE_UART_STOP_BIT 1
#define HPM_IP_FEATURE_UART_DISABLE_DMA_TIMEOUT 1
#define HPM_IP_FEATURE_UART_RX_LINE_ERROR_DETECT 1
#define HPM_IP_FEATURE_UART_DMA_STOP 1
#define HPM_IP_FEATURE_UART_BAUD_ACT_ENJ_PLCK 1
#define HPM_IP_FEATURE_UART_DE_DELAY 1
#define HPM_IP_FEATURE_UART_TXRX_POL 1

/* I2C related feature */
#define HPM_IP_FEATURE_I2C_SUPPORT_RESET 1

/* SPI related feature */
#define HPM_IP_FEATURE_SPI_NEW_TRANS_COUNT 1
#define HPM_IP_FEATURE_SPI_CS_SELECT 1
#define HPM_IP_FEATURE_SPI_SUPPORT_DIRECTIO 1
#define HPM_IP_FEATURE_SPI_DMA_TX_REQ_AFTER_CMD_FO_MASTER 1
#define HPM_IP_FEATURE_SPI_CS_EDGE_DETECT_FOR_SLAVE 1

/* EWDG related feature */
#define HPM_IP_FEATURE_EWDG_SOC_SUPPORT_TIMEOUT_INTERRUPT 1

/* DMAV2 related feature */
#define HPM_IP_FEATURE_DMAV2_BURST_IN_FIXED_TRANS 1
#define HPM_IP_FEATURE_DMAV2_BYTE_ORDER_SWAP 1

/* USB related feature */
#define HPM_IP_FEATURE_USB_CLK_SELECT 1

/* ADC16 related feature */
#define HPM_IP_FEATURE_ADC16_HAS_MOT_EN 1
#define HPM_IP_FEATURE_ADC16_HAS_DIFF_MODE 1
#define HPM_IP_FEATURE_ADC16_SEQ_HCFG_EN 1
#define HPM_IP_FEATURE_ADC16_HAS_TRIG_OUT 1
#define HPM_IP_FEATURE_ADC16_HAS_BUS_MODE_EN 1
#define HPM_IP_FEATURE_ADC16_SEQ_STOP_POS_INT 1
#define HPM_IP_FEATURE_ADC16_HAS_ADC_LOOP 1
#define HPM_IP_FEATURE_ADC16_HAS_DMA_SEQ16BIT 1
#define HPM_IP_FEATURE_ADC16_FORCE_SYNC_AHB 1

/* ACMP related feature */
#define HPM_IP_FEATURE_ACMP_HAS_CAP_SEL 1
#define HPM_IP_FEATURE_ACMP_DAC_MATRIX 1
#define HPM_IP_FEATURE_ACMP_12BIT_DAC 1

/* I2S related feature */
#define HPM_IP_FEATURE_I2S_HAS_SOFTWARE_RESET_STATUS 1
#define HPM_IP_FEATURE_I2S_BUFF_ALIGN_FRAME 1

/* PWM related feature */
#define HPM_IP_FEATURE_PWM_COUNTER_RESET 1

/* SYNT related feature */
#define HPM_IP_FEATURE_SYNT_TIMESTAMP 1
#define HPM_IP_FEATURE_SYNT_ONESHOT_MODE 1
#define HPM_IP_FEATURE_SYNT_CHAN16 1

/* TRGM related feature */
#define HPM_IP_FEATURE_TRGM_HAS_TRGM_IN_OUT_STATUS 1

/* PCFG related feature */
#define HPM_IP_FEATURE_PCFG_NO_DCDC 1

#endif /* HPM_SOC_IP_FEATURE_H */