/*
 * Copyright (c) 2023 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#ifndef HPM_MCL_CFG_H
#define HPM_MCL_CFG_H

#ifdef CONFIG_MCL_HAS_EXTRA_CONFIG
#include CONFIG_MCL_HAS_EXTRA_CONFIG
#endif

#ifndef MCL_EN_THETA_FORECAST
#define MCL_EN_THETA_FORECAST   (1)
#endif

#define MCL_CFG_EN_THETA_FORECAST   MCL_EN_THETA_FORECAST

#ifndef MCL_EN_DQ_AXIS_DECOUPLING_FUNCTION
#define MCL_EN_DQ_AXIS_DECOUPLING_FUNCTION   (1)
#endif

#define MCL_CFG_EN_DQ_AXIS_DECOUPLING   MCL_EN_DQ_AXIS_DECOUPLING_FUNCTION

#ifndef MCL_EN_DEAD_AREA_COMPENSATION
#define MCL_EN_DEAD_AREA_COMPENSATION   (1)
#endif

#define MCL_CFG_EN_DEAD_AREA_COMPENSATION MCL_EN_DEAD_AREA_COMPENSATION

#ifndef MCL_EN_SENSORLESS_SMC
#define MCL_EN_SENSORLESS_SMC       (1)
#endif

#define MCL_CFG_EN_SENSORLESS_SMC   MCL_EN_SENSORLESS_SMC

#ifndef MCL_USER_DEFINED_DEBUG_FIFO
#define MCL_USER_DEFINED_DEBUG_FIFO (100)
#endif

#endif
