
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_ahb0, 0);

    clock_add_to_group(clock_axif, 0);

    clock_add_to_group(clock_axis, 0);

    clock_add_to_group(clock_axic, 0);

    clock_add_to_group(clock_rom0, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_ram0, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_xdma, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_ptpc, 0);

    clock_add_to_group(clock_qei0, 0);

    clock_add_to_group(clock_plb0, 0);

    clock_add_to_group(clock_qei1, 0);

    clock_add_to_group(clock_qeo0, 0);

    clock_add_to_group(clock_qeo1, 0);

    clock_add_to_group(clock_pwm0, 0);

    clock_add_to_group(clock_pwm1, 0);

    clock_add_to_group(clock_emds, 0);
}

void init_board_clock_source(void)
{
    /* Generate pll0 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 960000000);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk0, pllctlv2_div_2p0);

    /* Generate clk1_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk1, pllctlv2_div_2p4);

    /* Generate clk_top_cpu0 code */
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart4_clock(void)
{
    clock_add_to_group(clock_uart4, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_i2c3_clock(void)
{
    clock_add_to_group(clock_i2c3, 0);
}

void init_spi1_clock(void)
{
    clock_add_to_group(clock_spi1, 0);
}

void init_spi3_clock(void)
{
    clock_add_to_group(clock_spi3, 0);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb0, clk_src_pll1_clk0, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc1_bus_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb0, clk_src_pll1_clk0, 2);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc1_analog_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ana1);
    clock_set_source_divider(clock_ana1, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc1, 0);
}

void init_can0_clock(void)
{
    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk0, 5);

    clock_add_to_group(clock_can0, 0);
}

void init_can1_clock(void)
{
    /* Generate clk_top_can1 code */
    clock_set_source_divider(clock_can1, clk_src_pll1_clk0, 5);

    clock_add_to_group(clock_can1, 0);
}

void init_can2_clock(void)
{
    /* Generate clk_top_can2 code */
    clock_set_source_divider(clock_can2, clk_src_pll1_clk0, 5);

    clock_add_to_group(clock_can2, 0);
}

void init_can3_clock(void)
{
    /* Generate clk_top_can3 code */
    clock_set_source_divider(clock_can3, clk_src_pll1_clk0, 5);

    clock_add_to_group(clock_can3, 0);
}

void init_ptp0_clock(void)
{
    /* Generate clk_top_ptp0 code */
    clock_set_source_divider(clock_ptp0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_ptp0, 0);
}

void init_eth0_clock(void)
{
    clock_add_to_group(clock_eth0, 0);
}

void init_esc0_clock(void)
{
    clock_add_to_group(clock_esc0, 0);
}

void init_eth0_rmii_ref_clock(void)
{
    /*
     * pll2_clk1 = PLL2(500MHz) / 2 = 250MHz; board_init_enet_rmii_reference_clock() already set PLL2 to 500MHz
     * Generate clk1_pll2 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL2, pllctlv2_clk1, pllctlv2_div_2p0);

    /*
     * eth0 = pll2_clk1 / 5 = 50MHz RMII reference
     * Generate clk_top_eth0 code
     */
    clock_set_source_divider(clock_eth0, clk_src_pll2_clk1, 5);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_gptmr2_clock(void)
{
    clock_add_to_group(clock_gptmr2, 0);
}

void init_gptmr3_clock(void)
{
    clock_add_to_group(clock_gptmr3, 0);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_acmp0_clock(void)
{
    clock_add_to_group(clock_acmp0, 0);
}

void init_owr0_clock(void)
{
    clock_add_to_group(clock_owire0, 0);
}
