/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef __ESP_HOSTED_WIFI_CONFIG_H__
#define __ESP_HOSTED_WIFI_CONFIG_H__

#include "esp_idf_version.h"
#include "esp_hosted_rpc.pb-c.h"

// dual band API support available
#define H_WIFI_DUALBAND_SUPPORT 0

#ifndef CONFIG_ESP_SPI_HOST_INTERFACE
#define CONFIG_ESP_SPI_HOST_INTERFACE 1
#endif

#ifndef CONFIG_ESP_SDIO_HOST_INTERFACE
#define CONFIG_ESP_SDIO_HOST_INTERFACE 0
#endif

/* default use SPI mode0*/
#ifndef ESP_HOSTED_SPI_MODE
#define ESP_HOSTED_SPI_MODE 0
#endif

#ifndef CONFIG_ESP_PKT_STATS
#define CONFIG_ESP_PKT_STATS 0
#endif

/* WiFi Configuration */
#ifndef CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM
#define CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM        16
#endif
#ifndef CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM
#define CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM       32
#endif

/* 1: Dynamic. 0:Static */
#ifndef CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER
#define CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER       1
#endif

#if CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER
#define CONFIG_ESP_WIFI_TX_BUFFER_TYPE              1
#else
#define CONFIG_ESP_WIFI_TX_BUFFER_TYPE              0
#endif

#ifndef CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF
#define CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM       32
#endif

#ifndef CONFIG_ESP_WIFI_AMPDU_TX_ENABLED
#define CONFIG_ESP_WIFI_AMPDU_TX_ENABLED            1
#endif

#ifndef CONFIG_ESP_WIFI_TX_BA_WIN
#define CONFIG_ESP_WIFI_TX_BA_WIN                   6
#endif

#ifndef CONFIG_ESP_WIFI_AMPDU_RX_ENABLED
#define CONFIG_ESP_WIFI_AMPDU_RX_ENABLED            1
#endif

#ifndef CONFIG_ESP_WIFI_RX_BA_WIN
#define CONFIG_ESP_WIFI_RX_BA_WIN                   6
#endif
#ifndef CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN
#define CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN       752
#endif
#ifndef CONFIG_ESP_WIFI_MGMT_SBUF_NUM
#define CONFIG_ESP_WIFI_MGMT_SBUF_NUM               32
#endif

#ifndef CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE
#define CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE  1
#endif

#ifndef CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM
#define CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM      7
#endif

/* BT Configuration TODO... */
#ifndef CONFIG_ESP_ENABLE_BT
#define CONFIG_ESP_ENABLE_BT                        0
#endif
#ifndef CONFIG_BT_NIMBLE_ENABLED
#define CONFIG_BT_NIMBLE_ENABLED                    0
#endif

/* RPC Configuration */
#ifndef CONFIG_ESP_MAX_SIMULTANEOUS_SYNC_RPC_REQUESTS
#define CONFIG_ESP_MAX_SIMULTANEOUS_SYNC_RPC_REQUESTS 8
#endif
#ifndef CONFIG_ESP_MAX_SIMULTANEOUS_ASYNC_RPC_REQUESTS
#define CONFIG_ESP_MAX_SIMULTANEOUS_ASYNC_RPC_REQUESTS 8
#endif

/* esp wifi comp */
#ifndef CONFIG_ESP_WIFI_CSI_ENABLED
#define CONFIG_ESP_WIFI_CSI_ENABLED 0
#endif

#ifndef CONFIG_ESP_WIFI_AMPDU_RX_ENABLED
#define CONFIG_ESP_WIFI_AMPDU_RX_ENABLED 0
#endif

#ifndef CONFIG_ESP_WIFI_AMPDU_TX_ENABLED
#define CONFIG_ESP_WIFI_AMPDU_TX_ENABLED 0
#endif

#ifndef CONFIG_ESP_WIFI_AMSDU_TX_ENABLED
#define CONFIG_ESP_WIFI_AMSDU_TX_ENABLED 0
#endif

#ifndef CONFIG_ESP_WIFI_NVS_ENABLED
#define CONFIG_ESP_WIFI_NVS_ENABLED 0
#endif

#ifndef CONFIG_NEWLIB_NANO_FORMAT
#define CONFIG_NEWLIB_NANO_FORMAT 0
#endif

#ifndef CONFIG_NEWLIB_NANO_FORMAT
#define CONFIG_NEWLIB_NANO_FORMAT 0
#endif

#ifndef CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE
#define CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE 1
#endif

#ifndef CONFIG_ESP_WIFI_ENABLE_WPA3_SAE
#define CONFIG_ESP_WIFI_ENABLE_WPA3_SAE 1
#endif

#ifndef CONFIG_ESP_WIFI_FTM_INITIATOR_SUPPORT
#define CONFIG_ESP_WIFI_FTM_INITIATOR_SUPPORT 0
#endif

#ifndef CONFIG_ESP_WIFI_FTM_RESPONDER_SUPPORT
#define CONFIG_ESP_WIFI_FTM_RESPONDER_SUPPORT 0
#endif

#ifndef CONFIG_ESP_WIFI_GCMP_SUPPORT
#define CONFIG_ESP_WIFI_GCMP_SUPPORT 0
#endif

#ifndef CONFIG_ESP_WIFI_GMAC_SUPPORT
#define CONFIG_ESP_WIFI_GMAC_SUPPORT 0
#endif

#ifndef CONFIG_ESP_WIFI_11R_SUPPORT
#define CONFIG_ESP_WIFI_11R_SUPPORT 0
#endif

#ifndef CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT
#define CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT 0
#endif

#ifndef CONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_1
#define CONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_1 0
#endif

#ifndef CONFIG_ESP_COEX_POWER_MANAGEMENT
#define CONFIG_ESP_COEX_POWER_MANAGEMENT 0
#endif

#ifndef CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT
#define CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT 0
#endif
#define H_WIFI_ENTERPRISE_SUPPORT CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT

#ifndef CONFIG_ESP_HOSTED_ENABLE_ITWT
#define CONFIG_ESP_HOSTED_ENABLE_ITWT 0
#endif

#ifndef CONFIG_SLAVE_SOC_WIFI_HE_SUPPORT
#define CONFIG_SLAVE_SOC_WIFI_HE_SUPPORT 0
#endif

#if CONFIG_ESP_HOSTED_ENABLE_ITWT && CONFIG_SLAVE_SOC_WIFI_HE_SUPPORT
  #define H_WIFI_HE_SUPPORT 1
#else
  #define H_WIFI_HE_SUPPORT 0
#endif

#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 4, 0)
#define H_PRESENT_IN_ESP_IDF_5_4_0      1
#else
#define H_PRESENT_IN_ESP_IDF_5_4_0      0
#endif

#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 5, 0)
#define H_PRESENT_IN_ESP_IDF_5_5_0      1
#else
#define H_PRESENT_IN_ESP_IDF_5_5_0      0
#endif

/* User-controllable reserved field decoding - works regardless of IDF version */
#ifndef CONFIG_ESP_HOSTED_DECODE_WIFI_RESERVED_FIELD
#define CONFIG_ESP_HOSTED_DECODE_WIFI_RESERVED_FIELD 0
#endif

#define H_DECODE_WIFI_RESERVED_FIELD CONFIG_ESP_HOSTED_DECODE_WIFI_RESERVED_FIELD

/* wifi_ap_config_t::transition_disable only found in
 * IDF v5.3.3 and above, or
 * IDF v5.4.1 and above
 */
#if (ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 3, 3)) || (ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 4, 1))
#define H_GOT_AP_CONFIG_PARAM_TRANSITION_DISABLE 0
#else
#define H_GOT_AP_CONFIG_PARAM_TRANSITION_DISABLE 1
#endif


#ifndef  CONFIG_ESP_HOSTED_DPP_SUPPORT
#define CONFIG_ESP_HOSTED_DPP_SUPPORT  0
#endif

#define H_DPP_SUPPORT CONFIG_ESP_HOSTED_DPP_SUPPORT

#endif /* __ESP_HOSTED_WIFI_CONFIG_H__ */
