
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_ahb, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_rom, 0);

    clock_add_to_group(clock_mot0, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_xpi0, 0);
}

void init_board_clock_source(void)
{
    /* Generate pll0 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 720000000);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk0, pllctlv2_div_1p0);

    /* Generate clk1_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk1, pllctlv2_div_1p2);

    /* Generate clk2_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk2, pllctlv2_div_1p8);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart3_clock(void)
{
    clock_add_to_group(clock_uart3, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_i2c3_clock(void)
{
    clock_add_to_group(clock_i2c3, 0);
}

void init_spi1_clock(void)
{
    clock_add_to_group(clock_spi1, 0);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll0_clk2, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_acmp0_clock(void)
{
    clock_add_to_group(clock_acmp0, 0);
}
