
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_ahbp, 0);

    clock_add_to_group(clock_axic, 0);

    clock_add_to_group(clock_axis, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_xpi1, 0);

    clock_add_to_group(clock_xdma, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_ram0, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_mot0, 0);

    clock_add_to_group(clock_mot1, 0);

    clock_add_to_group(clock_synt, 0);

    clock_add_to_group(clock_ptpc, 0);
}

void init_board_clock_source(void)
{
    /* Generate pll1 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 648000000);

    /* Generate clk0_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk0, pllctlv2_div_1p0);

    /* Generate clk1_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk1, pllctlv2_div_2p0);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart1_clock(void)
{
    clock_add_to_group(clock_uart1, 0);
}

void init_uart2_clock(void)
{
    clock_add_to_group(clock_uart2, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_i2c3_clock(void)
{
    clock_add_to_group(clock_i2c3, 0);
}

void init_spi3_clock(void)
{
    clock_add_to_group(clock_spi3, 0);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /*
     * Generate clk_top_adc0 code
     * Generate clk_top_ana0 code
     */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll0_clk1, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc1_bus_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ahb0);
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc1_analog_clock(void)
{
    /*
     * Generate clk_top_adc1 code
     * Generate clk_top_ana1 code
     */
    clock_set_adc_source(clock_adc1, clk_adc_src_ana1);
    clock_set_source_divider(clock_ana1, clk_src_pll0_clk1, 2);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc2_bus_clock(void)
{
    /* Generate clk_top_adc2 code */
    clock_set_adc_source(clock_adc2, clk_adc_src_ahb0);
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc2_analog_clock(void)
{
    /*
     * Generate clk_top_adc2 code
     * Generate clk_top_ana2 code
     */
    clock_set_adc_source(clock_adc2, clk_adc_src_ana2);
    clock_set_source_divider(clock_ana2, clk_src_pll0_clk1, 2);

    clock_add_to_group(clock_adc2, 0);
}

void init_dac0_ahb_clock(void)
{
    /* Generate clk_top_dac0 code */
    clock_set_dac_source(clock_dac0, clk_dac_src_ahb0);
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    clock_add_to_group(clock_dac0, 0);
}

void init_dac0_analog_clock(void)
{
    /*
     * Generate clk_top_dac0 code
     * Generate clk_top_ana3 code
     */
    clock_set_dac_source(clock_dac0, clk_dac_src_ana3);
    clock_set_source_divider(clock_ana3, clk_src_pll0_clk1, 2);

    clock_add_to_group(clock_dac0, 0);
}

void init_can0_clock(void)
{
    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll0_clk0, 5);

    clock_add_to_group(clock_can0, 0);
}

void init_can1_clock(void)
{
    /* Generate clk_top_can1 code */
    clock_set_source_divider(clock_can1, clk_src_pll0_clk0, 5);

    clock_add_to_group(clock_can1, 0);
}

void init_femc_clock(void)
{
    /* Generate clk_top_dram code */
    clock_set_source_divider(clock_femc, clk_src_pll0_clk1, 2);

    clock_add_to_group(clock_femc, 0);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr0_clock_group1(void)
{
    clock_add_to_group(clock_gptmr0, 1);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_gptmr1_clock_group1(void)
{
    clock_add_to_group(clock_gptmr1, 1);
}

void init_gptmr2_clock(void)
{
    clock_add_to_group(clock_gptmr2, 0);
}

void init_gptmr2_clock_group1(void)
{
    clock_add_to_group(clock_gptmr2, 1);
}

void init_gptmr3_clock(void)
{
    clock_add_to_group(clock_gptmr3, 0);
}

void init_gptmr3_clock_group1(void)
{
    clock_add_to_group(clock_gptmr3, 1);
}

void init_sdxc0_clock(void)
{
    clock_add_to_group(clock_sdxc0, 0);
}

void init_sdxc0_clock_source(void)
{
    /* Generate clk_top_sdc0 code */
    clock_set_source_divider(clock_sdxc0, clk_src_pll0_clk0, 2);
}

void init_enet_ptp0_clock(void)
{
    clock_add_to_group(clock_ptp0, 0);
}

void init_enet_ptp0_clock_group1(void)
{
    clock_add_to_group(clock_ptp0, 1);
}

void init_enet_ptp0_clock_source(void)
{
    /* Generate clk_top_ptp0 code */
    clock_set_source_divider(clock_ptp0, clk_src_pll0_clk0, 4);
}

void init_enet0_clock(void)
{
    clock_add_to_group(clock_eth0, 0);
}

void init_enet0_clock_group1(void)
{
    clock_add_to_group(clock_eth0, 1);
}

void init_enet0_rmii_reference_clock(void)
{
    /*
     * pll2_clk1 = PLL2(1GHz) / 4 = 250MHz; board_init_enet_rmii_reference_clock() already set PLL2 to 1GHz
     * Generate clk1_pll2 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL2, pllctlv2_clk1, pllctlv2_div_4p0);

    /*
     * eth0 = pll2_clk1 / 5 = 50MHz RMII reference
     * Generate clk_top_eth0 code
     */
    clock_set_source_divider(clock_eth0, clk_src_pll2_clk1, 5);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_ptmr_clock_group1(void)
{
    clock_add_to_group(clock_ptmr, 1);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_acmp_clock(void)
{
    clock_add_to_group(clock_acmp0, 0);
}
