
/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_uart0_pins(void);
void init_uart1_pins(void);
void init_uart2_pins(void);
void init_puart_pins(void);
void init_uart2_pins_as_gpio(void);
void init_i2c0_pins_as_gpio(void);
void init_i2c0_pins(void);
void init_i2c3_pins(void);
void init_femc_pins(void);
void init_gpio_pins_using_gpio0(void);
void init_spi3_pins(void);
void init_spi3_pins_with_gpio_as_cs(void);
void init_gptmr2_pins(void);
void init_hall_trgm_pins(void);
void init_qei_trgm_pins(void);
void init_butn_pins(void);
void init_acmp_pins(void);
void init_enet0_pins(void);
void init_pwm0_pins(void);
void init_adc_pins(void);
void init_adc_bldc_pins(void);
void init_can1_pins(void);
void init_sdxc0_cmd_pin_enable_opendrain(void);
void init_sdxc0_cmd_pin_disable_opendrain(void);
void init_sdxc0_cd_pin_as_gpio(void);
void init_sdxc0_cd_pin(void);
void init_sdxc0_clk_data_pins(void);
void init_sdxc0_clk_data_pins_width4(void);
void init_clk_obs_pins(void);
void init_led_pins(void);
void init_dac0_pins(void);
void init_enet_pps_pins(void);
void init_enet_pps_capture_pins(void);
void init_tamper_pins(void);
void init_uart_break_signal_pin(void);
void init_gptmr2_channel0_pin_as_output(void);
void init_gptmr2_channel1_pin_as_output(void);
void init_gptmr2_channel2_pin_as_output(void);
void init_gptmr2_channel0_pin_as_capture(void);
void init_brownout_indicate_pin(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
