
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#ifndef HPM_CLOCK_H
#define HPM_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

void init_board_clock(void);
void init_board_cpu1_clock(void);
void init_board_clock_source(void);
void init_femc_clock(void);
void init_uart0_clock(void);
void init_uart6_clock(void);
void init_uart13_clock(void);
void init_uart14_clock(void);
void init_i2c0_clock(void);
void init_i2c1_clock(void);
void init_i2c2_clock(void);
void init_i2c3_clock(void);
void init_i2c0_eeprom_clock(void);
void init_spi2_clock(void);
void init_usb0_clock(void);
void init_usb1_clock(void);
void init_acmp0_clock(void);
void init_acmp0_clock_group1(void);
void init_gptmr0_clock(void);
void init_gptmr0_clock_group1(void);
void init_gptmr1_clock(void);
void init_gptmr1_clock_group1(void);
void init_gptmr2_clock(void);
void init_gptmr2_clock_group1(void);
void init_gptmr3_clock(void);
void init_gptmr3_clock_group1(void);
void init_gptmr4_clock(void);
void init_gptmr4_clock_group1(void);
void init_gptmr5_clock(void);
void init_gptmr5_clock_group1(void);
void init_gptmr6_clock(void);
void init_gptmr6_clock_group1(void);
void init_gptmr7_clock(void);
void init_gptmr7_clock_group1(void);
void init_ptmr_clock(void);
void init_ptmr_clock_group1(void);
void init_cam0_clock(void);
void init_cam1_clock(void);
void init_dao_clock(void);
void init_pdm_clock(void);
void init_i2s0_clock(void);
void init_i2s0_clock_22050(void);
void init_i2s1_clock(void);
void init_i2s1_clock_22050(void);
void init_adc0_bus_clock(void);
void init_adc0_analog_clock(void);
void init_adc1_bus_clock(void);
void init_adc1_analog_clock(void);
void init_adc2_bus_clock(void);
void init_adc2_analog_clock(void);
void init_adc3_bus_clock(void);
void init_adc3_analog_clock(void);
void init_can0_clock(void);
void init_can1_clock(void);
void init_can2_clock(void);
void init_can3_clock(void);
void init_sdxc0_clock(void);
void init_sdxc0_clock_400khz(void);
void init_sdxc0_clock_24mhz(void);
void init_sdxc0_clock_50mhz(void);
void init_sdxc0_clock_100mhz(void);
void init_sdxc0_clock_166mhz(void);
void init_sdxc1_clock(void);
void init_sdxc1_clock_400khz(void);
void init_sdxc1_clock_24mhz(void);
void init_sdxc1_clock_50mhz(void);
void init_sdxc1_clock_100mhz(void);
void init_sdxc1_clock_166mhz(void);
void init_enet0_ptp_clock(void);
void init_enet0_ptp_clock_group1(void);
void init_enet1_ptp_clock(void);
void init_enet1_ptp_clock_group1(void);
void init_enet0_rmii_clock(void);
void init_enet0_rmii_clock_group1(void);
void init_enet1_rmii_clock(void);
void init_enet1_rmii_clock_group1(void);
void init_enet0_rgmii_clock(void);
void init_enet0_rgmii_clock_group1(void);
void init_enet_rmii_ref_pll2_postdiv(void);
void init_enet0_rmii_ref_clock(void);
void init_enet1_rmii_ref_clock(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_CLOCK_H */
