
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctl_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_axi0, 0);

    clock_add_to_group(clock_axi1, 0);

    clock_add_to_group(clock_axi2, 0);

    clock_add_to_group(clock_ahb, 0);

    clock_add_to_group(clock_xdma, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_xpi1, 0);

    clock_add_to_group(clock_ram0, 0);

    clock_add_to_group(clock_ram1, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_lmm1, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_mot0, 0);

    clock_add_to_group(clock_mot1, 0);

    clock_add_to_group(clock_mot2, 0);

    clock_add_to_group(clock_mot3, 0);

    clock_add_to_group(clock_synt, 0);

    clock_add_to_group(clock_ptpc, 0);
}

void init_board_cpu1_clock(void)
{
    clock_add_to_group(clock_cpu1, 1);

    clock_add_to_group(clock_mchtmr1, 1);
}

void init_board_clock_source(void)
{
    /* Generate clk_top_cpu0 code */
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    /* Generate clk_top_cpu1 code */
    clock_set_source_divider(clock_cpu1, clk_src_pll0_clk0, 1);

    /* Generate clk_top_ahb code */
    clock_set_source_divider(clock_ahb, clk_src_pll1_clk1, 2);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);

    /* Generate clk_top_mct1 code */
    clock_set_source_divider(clock_mchtmr1, clk_src_osc24m, 1);
}

void init_femc_clock(void)
{
    /* Generate clk_top_femc code */
    clock_set_source_divider(clock_femc, clk_src_pll2_clk0, 2);

    clock_add_to_group(clock_femc, 0);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart6_clock(void)
{
    clock_add_to_group(clock_uart6, 0);
}

void init_uart13_clock(void)
{
    clock_add_to_group(clock_uart13, 0);
}

void init_uart14_clock(void)
{
    clock_add_to_group(clock_uart14, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_i2c3_clock(void)
{
    clock_add_to_group(clock_i2c3, 0);
}

void init_i2c0_eeprom_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_spi2_clock(void)
{
    clock_add_to_group(clock_spi2, 0);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_usb1_clock(void)
{
    clock_add_to_group(clock_usb1, 0);
}

void init_acmp0_clock(void)
{
    clock_add_to_group(clock_acmp0, 0);
}

void init_acmp0_clock_group1(void)
{
    clock_add_to_group(clock_acmp0, 1);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr0_clock_group1(void)
{
    clock_add_to_group(clock_gptmr0, 1);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_gptmr1_clock_group1(void)
{
    clock_add_to_group(clock_gptmr1, 1);
}

void init_gptmr2_clock(void)
{
    clock_add_to_group(clock_gptmr2, 0);
}

void init_gptmr2_clock_group1(void)
{
    clock_add_to_group(clock_gptmr2, 1);
}

void init_gptmr3_clock(void)
{
    clock_add_to_group(clock_gptmr3, 0);
}

void init_gptmr3_clock_group1(void)
{
    clock_add_to_group(clock_gptmr3, 1);
}

void init_gptmr4_clock(void)
{
    clock_add_to_group(clock_gptmr4, 0);
}

void init_gptmr4_clock_group1(void)
{
    clock_add_to_group(clock_gptmr4, 1);
}

void init_gptmr5_clock(void)
{
    clock_add_to_group(clock_gptmr5, 0);
}

void init_gptmr5_clock_group1(void)
{
    clock_add_to_group(clock_gptmr5, 1);
}

void init_gptmr6_clock(void)
{
    clock_add_to_group(clock_gptmr6, 0);
}

void init_gptmr6_clock_group1(void)
{
    clock_add_to_group(clock_gptmr6, 1);
}

void init_gptmr7_clock(void)
{
    clock_add_to_group(clock_gptmr7, 0);
}

void init_gptmr7_clock_group1(void)
{
    clock_add_to_group(clock_gptmr7, 1);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_ptmr_clock_group1(void)
{
    clock_add_to_group(clock_ptmr, 1);
}

void init_cam0_clock(void)
{
    /* Generate clk_top_cam0 code */
    clock_set_source_divider(clock_camera0, clk_src_osc24m, 1);

    clock_add_to_group(clock_camera0, 0);
}

void init_cam1_clock(void)
{
    /* Generate clk_top_cam1 code */
    clock_set_source_divider(clock_camera1, clk_src_osc24m, 1);

    clock_add_to_group(clock_camera1, 0);
}

void init_dao_clock(void)
{
    clock_add_to_group(clock_dao, 0);
}

void init_pdm_clock(void)
{
    clock_add_to_group(clock_pdm, 0);
}

void init_i2s0_clock(void)
{
    /*
     * Generate clk_top_i2s0 code
     * Generate clk_top_aud0 code
     */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll3_clk0, 25);

    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s0_clock_22050(void)
{
    /*
     * Generate clk_top_i2s0 code
     * Generate clk_top_aud0 code
     */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll3_clk0, 54);

    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s1_clock(void)
{
    /*
     * Generate clk_top_i2s1 code
     * Generate clk_top_aud1 code
     */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll3_clk0, 25);

    clock_add_to_group(clock_i2s1, 0);
}

void init_i2s1_clock_22050(void)
{
    /*
     * Generate clk_top_i2s1 code
     * Generate clk_top_aud1 code
     */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll3_clk0, 54);

    clock_add_to_group(clock_i2s1, 0);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /*
     * Generate clk_top_adc0 code
     * Generate clk_top_ana0 code
     */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc1_bus_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc1_analog_clock(void)
{
    /*
     * Generate clk_top_adc1 code
     * Generate clk_top_ana1 code
     */
    clock_set_adc_source(clock_adc1, clk_adc_src_ana1);
    clock_set_source_divider(clock_ana1, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc2_bus_clock(void)
{
    /* Generate clk_top_adc2 code */
    clock_set_adc_source(clock_adc2, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc2_analog_clock(void)
{
    /*
     * Generate clk_top_adc2 code
     * Generate clk_top_ana2 code
     */
    clock_set_adc_source(clock_adc2, clk_adc_src_ana2);
    clock_set_source_divider(clock_ana2, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc3_bus_clock(void)
{
    /* Generate clk_top_adc3 code */
    clock_set_adc_source(clock_adc3, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc3, 0);
}

void init_adc3_analog_clock(void)
{
    /*
     * Generate clk_top_adc3 code
     * Generate clk_top_ana2 code
     */
    clock_set_adc_source(clock_adc3, clk_adc_src_ana2);
    clock_set_source_divider(clock_ana2, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_adc3, 0);
}

void init_can0_clock(void)
{
    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk1, 5);

    clock_add_to_group(clock_can0, 0);
}

void init_can1_clock(void)
{
    /* Generate clk_top_can1 code */
    clock_set_source_divider(clock_can1, clk_src_pll1_clk1, 5);

    clock_add_to_group(clock_can1, 0);
}

void init_can2_clock(void)
{
    /* Generate clk_top_can2 code */
    clock_set_source_divider(clock_can2, clk_src_pll1_clk1, 5);

    clock_add_to_group(clock_can2, 0);
}

void init_can3_clock(void)
{
    /* Generate clk_top_can3 code */
    clock_set_source_divider(clock_can3, clk_src_pll1_clk1, 5);

    clock_add_to_group(clock_can3, 0);
}

void init_sdxc0_clock(void)
{
    clock_add_to_group(clock_sdxc0, 0);
}

void init_sdxc0_clock_400khz(void)
{
    /* Generate clk_top_sdxc0 code */
    clock_set_source_divider(clock_sdxc0, clk_src_osc24m, 63);
}

void init_sdxc0_clock_24mhz(void)
{
    /* Generate clk_top_sdxc0 code */
    clock_set_source_divider(clock_sdxc0, clk_src_osc24m, 1);
}

void init_sdxc0_clock_50mhz(void)
{
    /* Generate clk_top_sdxc0 code */
    clock_set_source_divider(clock_sdxc0, clk_src_pll1_clk1, 8);
}

void init_sdxc0_clock_100mhz(void)
{
    /* Generate clk_top_sdxc0 code */
    clock_set_source_divider(clock_sdxc0, clk_src_pll1_clk1, 4);
}

void init_sdxc0_clock_166mhz(void)
{
    /* Generate clk_top_sdxc0 code */
    clock_set_source_divider(clock_sdxc0, clk_src_pll2_clk0, 2);
}

void init_sdxc1_clock(void)
{
    clock_add_to_group(clock_sdxc1, 0);
}

void init_sdxc1_clock_400khz(void)
{
    /* Generate clk_top_sdxc1 code */
    clock_set_source_divider(clock_sdxc1, clk_src_osc24m, 63);
}

void init_sdxc1_clock_24mhz(void)
{
    /* Generate clk_top_sdxc1 code */
    clock_set_source_divider(clock_sdxc1, clk_src_osc24m, 1);
}

void init_sdxc1_clock_50mhz(void)
{
    /* Generate clk_top_sdxc1 code */
    clock_set_source_divider(clock_sdxc1, clk_src_pll1_clk1, 8);
}

void init_sdxc1_clock_100mhz(void)
{
    /* Generate clk_top_sdxc1 code */
    clock_set_source_divider(clock_sdxc1, clk_src_pll1_clk1, 4);
}

void init_sdxc1_clock_166mhz(void)
{
    /* Generate clk_top_sdxc1 code */
    clock_set_source_divider(clock_sdxc1, clk_src_pll2_clk0, 2);
}

void init_enet0_ptp_clock(void)
{
    /* Generate clk_top_ptp0 code */
    clock_set_source_divider(clock_ptp0, clk_src_pll1_clk1, 4);

    clock_add_to_group(clock_ptp0, 0);
}

void init_enet0_ptp_clock_group1(void)
{
    /* Generate clk_top_ptp0 code */
    clock_set_source_divider(clock_ptp0, clk_src_pll1_clk1, 4);

    clock_add_to_group(clock_ptp0, 1);
}

void init_enet1_ptp_clock(void)
{
    /* Generate clk_top_ptp1 code */
    clock_set_source_divider(clock_ptp1, clk_src_pll1_clk1, 4);

    clock_add_to_group(clock_ptp1, 0);
}

void init_enet1_ptp_clock_group1(void)
{
    /* Generate clk_top_ptp1 code */
    clock_set_source_divider(clock_ptp1, clk_src_pll1_clk1, 4);

    clock_add_to_group(clock_ptp1, 1);
}

void init_enet0_rmii_clock(void)
{
    clock_add_to_group(clock_eth0, 0);
}

void init_enet0_rmii_clock_group1(void)
{
    clock_add_to_group(clock_eth0, 1);
}

void init_enet1_rmii_clock(void)
{
    clock_add_to_group(clock_eth1, 0);
}

void init_enet1_rmii_clock_group1(void)
{
    clock_add_to_group(clock_eth1, 1);
}

void init_enet0_rgmii_clock(void)
{
    clock_add_to_group(clock_eth0, 0);
}

void init_enet0_rgmii_clock_group1(void)
{
    clock_add_to_group(clock_eth0, 1);
}

void init_enet_rmii_ref_pll2_postdiv(void)
{
    /*
     * pll2_clk1 = PLL2(1GHz) / 4 = 250MHz; board_init_enet_rmii_reference_clock() already set PLL2 to 1GHz
     * Generate clk1_pll2 code
     */
    pllctl_set_div(HPM_PLLCTL, PLLCTL_PLL_PLL2, 1, 4);
}

void init_enet0_rmii_ref_clock(void)
{
    /*
     * eth0 = pll2_clk1 / 5 = 50MHz RMII reference
     * Generate clk_top_enet0 code
     */
    clock_set_source_divider(clock_eth0, clk_src_pll2_clk1, 5);
}

void init_enet1_rmii_ref_clock(void)
{
    /*
     * eth1 = pll2_clk1 / 5 = 50MHz RMII reference
     * Generate clk_top_enet1 code
     */
    clock_set_source_divider(clock_eth1, clk_src_pll2_clk1, 5);
}
