# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # Install Python dependencies first
    - pip install -r docs/requirements.txt
    # Build prerequisites: API documentation and cmake_intro
    - cd docs && make api_doc
    - cd docs && make cmake_intro
    # Build Sphinx HTML documentation using Makefile (outputs to output/en/html)
    # Then copy to Read the Docs expected location
    - cd docs && make en
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/output/en/html/* $READTHEDOCS_OUTPUT/html/
    # Copy api_doc into HTML output directory so it's accessible via web
    # Doxygen outputs to output/api_doc/html/, we copy the html directory contents
    # This allows access via api_doc/index.html relative to the HTML root
    # Note: We're back at repo root after the cd commands, so use docs/output/...
    - |
      if [ -d "docs/output/api_doc/html" ]; then
        cp -r docs/output/api_doc/html $READTHEDOCS_OUTPUT/html/api_doc
        echo "api_doc copied successfully to $READTHEDOCS_OUTPUT/html/api_doc"
        ls -la $READTHEDOCS_OUTPUT/html/api_doc/ | head -10 || true
      else
        echo "Error: docs/output/api_doc/html not found"
        echo "Checking docs/output/api_doc structure:"
        ls -la docs/output/api_doc/ 2>/dev/null || echo "docs/output/api_doc directory does not exist"
        echo "Checking docs/output structure:"
        ls -la docs/output/ 2>/dev/null || echo "docs/output directory does not exist"
      fi
