
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_ahb, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_rom, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_hdma0, 0);

    clock_add_to_group(clock_hdma1, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_ptpc, 0);

    clock_add_to_group(clock_emds, 0);

    clock_add_to_group(clock_pwm0, 0);

    clock_add_to_group(clock_pwm1, 0);

    clock_add_to_group(clock_pwm2, 0);

    clock_add_to_group(clock_pwm3, 0);
}

void init_cpu_clock(void)
{
    /* Generate pll0 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 800000000);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk0, pllctlv2_div_1p0);

    /* Generate clk_top_cpu0 code */
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 2);
}

void init_mchtmr_clock(void)
{
    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_spi0_clock(void)
{
    clock_add_to_group(clock_spi0, 0);
}

void init_spi3_clock(void)
{
    clock_add_to_group(clock_spi3, 0);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /*
     * Generate clk_top_adc0 code
     * Generate clk_top_ana0 code
     */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 2);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc1_bus_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ahb0);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc1_analog_clock(void)
{
    /*
     * Generate clk_top_adc1 code
     * Generate clk_top_ana1 code
     */
    clock_set_adc_source(clock_adc1, clk_adc_src_ana1);
    clock_set_source_divider(clock_ana1, clk_src_pll1_clk0, 2);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc2_bus_clock(void)
{
    /* Generate clk_top_adc2 code */
    clock_set_adc_source(clock_adc2, clk_adc_src_ahb0);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc2_analog_clock(void)
{
    /*
     * Generate clk_top_adc2 code
     * Generate clk_top_ana2 code
     */
    clock_set_adc_source(clock_adc2, clk_adc_src_ana2);
    clock_set_source_divider(clock_ana2, clk_src_pll1_clk0, 2);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc3_bus_clock(void)
{
    /* Generate clk_top_adc3 code */
    clock_set_adc_source(clock_adc3, clk_adc_src_ahb0);

    clock_add_to_group(clock_adc3, 0);
}

void init_adc3_analog_clock(void)
{
    /*
     * Generate clk_top_adc3 code
     * Generate clk_top_ana3 code
     */
    clock_set_adc_source(clock_adc3, clk_adc_src_ana3);
    clock_set_source_divider(clock_ana3, clk_src_pll1_clk0, 2);

    clock_add_to_group(clock_adc3, 0);
}

void init_acmp0_clock(void)
{
    clock_add_to_group(clock_acmp0, 0);
}

void init_acmp0_clock_group1(void)
{
    clock_add_to_group(clock_acmp0, 1);
}

void init_can0_clock(void)
{
    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk0, 5);

    clock_add_to_group(clock_can0, 0);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart1_clock(void)
{
    clock_add_to_group(clock_uart1, 0);
}

void init_uart2_clock(void)
{
    clock_add_to_group(clock_uart2, 0);
}

void init_uart3_clock(void)
{
    clock_add_to_group(clock_uart3, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr0_clock_group1(void)
{
    clock_add_to_group(clock_gptmr0, 1);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_gptmr1_clock_group1(void)
{
    clock_add_to_group(clock_gptmr1, 1);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_ptmr_clock_group1(void)
{
    clock_add_to_group(clock_ptmr, 1);
}

void init_i2s0_clock_22050(void)
{
    /*
     * Generate clk_top_i2s0 code
     * Generate clk_top_aud0 code
     */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll2_clk1, 20);

    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s0_clock_default(void)
{
    /*
     * Generate clk_top_i2s0 code
     * Generate clk_top_aud0 code
     */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll2_clk0, 21);

    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s1_clock_22050(void)
{
    /*
     * Generate clk_top_i2s1 code
     * Generate clk_top_aud1 code
     */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll2_clk1, 20);

    clock_add_to_group(clock_i2s1, 0);
}

void init_i2s1_clock_default(void)
{
    /*
     * Generate clk_top_i2s1 code
     * Generate clk_top_aud1 code
     */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll2_clk0, 21);

    clock_add_to_group(clock_i2s1, 0);
}
