
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_uart0_pins(void);
void init_uart2_pins(void);
void init_uart3_pins(void);
void init_uart3_pin_as_gpio(void);
void init_i2c0_pins(void);
void init_i2c1_pins(void);
void init_i2c2_pins(void);
void init_i2s0_pins(void);
void init_spi3_pins(void);
void init_spi3_pins_with_gpio_as_cs(void);
void init_gptmr0_pins(void);
void init_gpio_pins(void);
void init_butn_pins(void);
void init_acmp_pins(void);
void init_pwm0_pins(void);
void init_pwm1_pins(void);
void init_pwm2_pins(void);
void init_pwm3_pins(void);
void init_adc_pins(void);
void init_adc16_diff_pins(void);
void init_adc_bldc_pins(void);
void init_adc_qeiv2_pins(void);
void init_usb0_pins(void);
void init_mcan0_pins(void);
void init_led_pins_as_gpio(void);
void init_led_pins_as_pwm(void);
void init_opamp_pins(void);
void init_uart_break_signal_pin(void);
void init_gptmr0_channel0_pin_as_output(void);
void init_gptmr0_channel1_pin_as_output(void);
void init_gptmr0_channel3_pin_as_output(void);
void init_gptmr0_channel0_pin_as_capture(void);
void init_clk_ref_pin(void);
void init_brownout_indicate_pin(void);
void init_trgm_gptmr0_cap2_invert_pins(void);
void init_spi_nor_flash_pins(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
