/*
 * Copyright (c) 2024 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef __HPM_PMBUS_CMD_H
#define __HPM_PMBUS_CMD_H


/* Define Command macros, support 1.2 version */
#define PMBUS_CODE_PAGE                           0x00
#define PMBUS_CODE_OPERATION                      0x01
#define PMBUS_CODE_ON_OFF_CONFIG                  0x02
#define PMBUS_CODE_CLEAR_FAULTS                   0x03
#define PMBUS_CODE_PHASE                          0x04
#define PMBUS_CODE_PAGE_PLUS_WRITE                0x05
#define PMBUS_CODE_PAGE_PLUS_READ                 0x06
#define PMBUS_CODE_RESERVED_1                     0x07
#define PMBUS_CODE_RESERVED_2                     0x08
#define PMBUS_CODE_RESERVED_3                     0x09
#define PMBUS_CODE_RESERVED_4                     0x0A
#define PMBUS_CODE_RESERVED_5                     0x0B
#define PMBUS_CODE_RESERVED_6                     0x0C
#define PMBUS_CODE_RESERVED_7                     0x0D
#define PMBUS_CODE_RESERVED_8                     0x0E
#define PMBUS_CODE_RESERVED_9                     0x0F
#define PMBUS_CODE_WRITE_PROTECT                  0x10
#define PMBUS_CODE_STORE_DEFAULT_ALL              0x11
#define PMBUS_CODE_RESTORE_DEFAULT_ALL            0x12
#define PMBUS_CODE_STORE_DEFAULT_CODE             0x13
#define PMBUS_CODE_RESTORE_DEFAULT_CODE           0x14
#define PMBUS_CODE_STORE_USER_ALL                 0x15
#define PMBUS_CODE_RESTORE_USER_ALL               0x16
#define PMBUS_CODE_STORE_USER_CODE                0x17
#define PMBUS_CODE_RESTORE_USER_CODE              0x18
#define PMBUS_CODE_CAPABILITY                     0x19
#define PMBUS_CODE_QUERY                          0x1A
#define PMBUS_CODE_SMBALERT_MASK                  0x1B
#define PMBUS_CODE_RESERVED_10                    0x1C
#define PMBUS_CODE_RESERVED_11                    0x1D
#define PMBUS_CODE_RESERVED_12                    0x1E
#define PMBUS_CODE_RESERVED_13                    0x1F
#define PMBUS_CODE_VOUT_MODE                      0x20
#define PMBUS_CODE_VOUT_COMMAND                   0x21
#define PMBUS_CODE_VOUT_TRIM                      0x22
#define PMBUS_CODE_VOUT_CAL_OFFSET                0x23
#define PMBUS_CODE_VOUT_MAX                       0x24
#define PMBUS_CODE_VOUT_MARGIN_HIGH               0x25
#define PMBUS_CODE_VOUT_MARGIN_LOW                0x26
#define PMBUS_CODE_VOUT_TRANSITION_RATE           0x27
#define PMBUS_CODE_VOUT_DROOP                     0x28
#define PMBUS_CODE_VOUT_SCALE_LOOP                0x29
#define PMBUS_CODE_VOUT_SCALE_MONITOR             0x2A
#define PMBUS_CODE_RESERVED_14                    0x2B
#define PMBUS_CODE_RESERVED_15                    0x2C
#define PMBUS_CODE_RESERVED_16                    0x2D
#define PMBUS_CODE_RESERVED_17                    0x2E
#define PMBUS_CODE_RESERVED_18                    0x2F
#define PMBUS_CODE_COEFFICIENTS                   0x30
#define PMBUS_CODE_POUT_MAX                       0x31
#define PMBUS_CODE_MAX_DUTY                       0x32
#define PMBUS_CODE_FREQUENCY_SWITCH               0x33
#define PMBUS_CODE_RESERVED_19                    0x34
#define PMBUS_CODE_VIN_ON                         0x35
#define PMBUS_CODE_VIN_OFF                        0x36
#define PMBUS_CODE_INTERLEAVE                     0x37
#define PMBUS_CODE_IOUT_CAL_GAIN                  0x38
#define PMBUS_CODE_IOUT_CAL_OFFSET                0x39
#define PMBUS_CODE_FAN_CONFIG_1_2                 0x3A
#define PMBUS_CODE_FAN_COMMAND_1                  0x3B
#define PMBUS_CODE_FAN_COMMAND_2                  0x3C
#define PMBUS_CODE_FAN_CONFIG_3_4                 0x3D
#define PMBUS_CODE_FAN_COMMAND_3                  0x3E
#define PMBUS_CODE_FAN_COMMAND_4                  0x3F
#define PMBUS_CODE_VOUT_OV_FAULT_LIMIT            0x40
#define PMBUS_CODE_VOUT_OV_FAULT_RESPONSE         0x41
#define PMBUS_CODE_VOUT_OV_WARN_LIMIT             0x42
#define PMBUS_CODE_VOUT_UV_WARN_LIMIT             0x43
#define PMBUS_CODE_VOUT_UV_FAULT_LIMIT            0x44
#define PMBUS_CODE_VOUT_UV_FAULT_RESPONSE         0x45
#define PMBUS_CODE_IOUT_OC_FAULT_LIMIT            0x46
#define PMBUS_CODE_IOUT_OC_FAULT_RESPONSE         0x47
#define PMBUS_CODE_IOUT_OC_LV_FAULT_LIMIT         0x48
#define PMBUS_CODE_IOUT_OC_LV_FAULT_RESPONSE      0x49
#define PMBUS_CODE_IOUT_OC_WARN_LIMIT             0x4A
#define PMBUS_CODE_IOUT_UC_FAULT_LIMIT            0x4B
#define PMBUS_CODE_IOUT_UC_FAULT_RESPONSE         0x4C
#define PMBUS_CODE_RESERVED_20                    0x4D
#define PMBUS_CODE_RESERVED_21                    0x4E
#define PMBUS_CODE_OT_FAULT_LIMIT                 0x4F
#define PMBUS_CODE_OT_FAULT_RESPONSE              0x50
#define PMBUS_CODE_OT_WARN_LIMIT                  0x51
#define PMBUS_CODE_UT_WARN_LIMIT                  0x52
#define PMBUS_CODE_UT_FAULT_LIMIT                 0x53
#define PMBUS_CODE_UT_FAULT_RESPONSE              0x54
#define PMBUS_CODE_VIN_OV_FAULT_LIMIT             0x55
#define PMBUS_CODE_VIN_OV_FAULT_RESPONSE          0x56
#define PMBUS_CODE_VIN_OV_WARN_LIMIT              0x57
#define PMBUS_CODE_VIN_UV_WARN_LIMIT              0x58
#define PMBUS_CODE_VIN_UV_FAULT_LIMIT             0x59
#define PMBUS_CODE_VIN_UV_FAULT_RESPONSE          0x5A
#define PMBUS_CODE_IIN_OC_FAULT_LIMIT             0x5B
#define PMBUS_CODE_IIN_OC_FAULT_RESPONSE          0x5C
#define PMBUS_CODE_IIN_OC_WARN_LIMIT              0x5D
#define PMBUS_CODE_POWER_GOOD_ON                  0x5E
#define PMBUS_CODE_POWER_GOOD_OFF                 0x5F
#define PMBUS_CODE_TON_DELAY                      0x60
#define PMBUS_CODE_TON_RISE                       0x61
#define PMBUS_CODE_TON_MAX_FAULT_LIMIT            0x62
#define PMBUS_CODE_TON_MAX_FAULT_RESPONSE         0x63
#define PMBUS_CODE_TOFF_DELAY                     0x64
#define PMBUS_CODE_TOFF_FALL                      0x65
#define PMBUS_CODE_TOFF_MAX_WARN_LIMIT            0x66
#define PMBUS_CODE_RESERVED_22                    0x67
#define PMBUS_CODE_POUT_OP_FAULT_LIMIT            0x68
#define PMBUS_CODE_POUT_OP_FAULT_RESPONSE         0x69
#define PMBUS_CODE_POUT_OP_WARN_LIMIT             0x6A
#define PMBUS_CODE_PIN_OP_WARN_LIMIT              0x6B
#define PMBUS_CODE_RESERVED_23                    0x6C
#define PMBUS_CODE_RESERVED_24                    0x6D
#define PMBUS_CODE_RESERVED_25                    0x6E
#define PMBUS_CODE_RESERVED_26                    0x6F
#define PMBUS_CODE_RESERVED_27                    0x70
#define PMBUS_CODE_RESERVED_28                    0x71
#define PMBUS_CODE_RESERVED_29                    0x72
#define PMBUS_CODE_RESERVED_30                    0x73
#define PMBUS_CODE_RESERVED_31                    0x74
#define PMBUS_CODE_RESERVED_32                    0x75
#define PMBUS_CODE_RESERVED_33                    0x76
#define PMBUS_CODE_RESERVED_34                    0x77
#define PMBUS_CODE_STATUS_BYTE                    0x78
#define PMBUS_CODE_STATUS_WORD                    0x79
#define PMBUS_CODE_STATUS_VOUT                    0x7A
#define PMBUS_CODE_STATUS_IOUT                    0x7B
#define PMBUS_CODE_STATUS_INPUT                   0x7C
#define PMBUS_CODE_STATUS_TEMPERATURE             0x7D
#define PMBUS_CODE_STATUS_CML                     0x7E
#define PMBUS_CODE_STATUS_OTHER                   0x7F
#define PMBUS_CODE_STATUS_MFR_SPECIFIC            0x80
#define PMBUS_CODE_STATUS_FANS_1_2                0x81
#define PMBUS_CODE_STATUS_FANS_3_4                0x82
#define PMBUS_CODE_RESERVED_35                    0x83
#define PMBUS_CODE_RESERVED_36                    0x84
#define PMBUS_CODE_RESERVED_37                    0x85
#define PMBUS_CODE_READ_EIN                       0x86
#define PMBUS_CODE_READ_EOUT                      0x87
#define PMBUS_CODE_READ_VIN                       0x88
#define PMBUS_CODE_READ_IIN                       0x89
#define PMBUS_CODE_READ_VCAP                      0x8A
#define PMBUS_CODE_READ_VOUT                      0x8B
#define PMBUS_CODE_READ_IOUT                      0x8C
#define PMBUS_CODE_READ_TEMPERATURE_1             0x8D
#define PMBUS_CODE_READ_TEMPERATURE_2             0x8E
#define PMBUS_CODE_READ_TEMPERATURE_3             0x8F
#define PMBUS_CODE_READ_FAN_SPEED_1               0x90
#define PMBUS_CODE_READ_FAN_SPEED_2               0x91
#define PMBUS_CODE_READ_FAN_SPEED_3               0x92
#define PMBUS_CODE_READ_FAN_SPEED_4               0x93
#define PMBUS_CODE_READ_DUTY_CYCLE                0x94
#define PMBUS_CODE_READ_FREQUENCY                 0x95
#define PMBUS_CODE_READ_POUT                      0x96
#define PMBUS_CODE_READ_PIN                       0x97
#define PMBUS_CODE_PMBUS_REVISION                 0x98
#define PMBUS_CODE_MFR_ID                         0x99
#define PMBUS_CODE_MFR_MODEL                      0x9A
#define PMBUS_CODE_MFR_REVISION                   0x9B
#define PMBUS_CODE_MFR_LOCATION                   0x9C
#define PMBUS_CODE_MFR_DATE                       0x9D
#define PMBUS_CODE_MFR_SERIAL                     0x9E
#define PMBUS_CODE_APP_PROFILE_SUPPORT            0x9F
#define PMBUS_CODE_MFR_VIN_MIN                    0xA0
#define PMBUS_CODE_MFR_VIN_MAX                    0xA1
#define PMBUS_CODE_MFR_IIN_MAX                    0xA2
#define PMBUS_CODE_MFR_PIN_MAX                    0xA3
#define PMBUS_CODE_MFR_VOUT_MIN                   0xA4
#define PMBUS_CODE_MFR_VOUT_MAX                   0xA5
#define PMBUS_CODE_MFR_IOUT_MAX                   0xA6
#define PMBUS_CODE_MFR_POUT_MAX                   0xA7
#define PMBUS_CODE_MFR_TAMBIENT_MAX               0xA8
#define PMBUS_CODE_MFR_TAMBIENT_MIN               0xA9
#define PMBUS_CODE_MFR_EFFICIENCY_LL              0xAA
#define PMBUS_CODE_MFR_EFFICIENCY_HL              0xAB
#define PMBUS_CODE_MFR_PIN_ACCURACY               0xAC
#define PMBUS_CODE_IC_DEVICE_ID                   0xAD
#define PMBUS_CODE_IC_DEVICE_REV                  0xAE
#define PMBUS_CODE_RESERVED_38                    0xAF
#define PMBUS_CODE_USER_DATA_00                   0xB0
#define PMBUS_CODE_USER_DATA_01                   0xB1
#define PMBUS_CODE_USER_DATA_02                   0xB2
#define PMBUS_CODE_USER_DATA_03                   0xB3
#define PMBUS_CODE_USER_DATA_04                   0xB4
#define PMBUS_CODE_USER_DATA_05                   0xB5
#define PMBUS_CODE_USER_DATA_06                   0xB6
#define PMBUS_CODE_USER_DATA_07                   0xB7
#define PMBUS_CODE_USER_DATA_08                   0xB8
#define PMBUS_CODE_USER_DATA_09                   0xB9
#define PMBUS_CODE_USER_DATA_10                   0xBA
#define PMBUS_CODE_USER_DATA_11                   0xBB
#define PMBUS_CODE_USER_DATA_12                   0xBC
#define PMBUS_CODE_USER_DATA_13                   0xBD
#define PMBUS_CODE_USER_DATA_14                   0xBE
#define PMBUS_CODE_USER_DATA_15                   0xBF
#define PMBUS_CODE_MFR_MAX_TEMP_1                 0xC0
#define PMBUS_CODE_MFR_MAX_TEMP_2                 0xC1
#define PMBUS_CODE_MFR_MAX_TEMP_3                 0xC2
#define PMBUS_CODE_RESERVED_39                    0xC3
#define PMBUS_CODE_RESERVED_40                    0xC4
#define PMBUS_CODE_RESERVED_41                    0xC5
#define PMBUS_CODE_RESERVED_42                    0xC6
#define PMBUS_CODE_RESERVED_43                    0xC7
#define PMBUS_CODE_RESERVED_44                    0xC8
#define PMBUS_CODE_RESERVED_45                    0xC9
#define PMBUS_CODE_RESERVED_46                    0xCA
#define PMBUS_CODE_RESERVED_47                    0xCB
#define PMBUS_CODE_RESERVED_48                    0xCC
#define PMBUS_CODE_RESERVED_49                    0xCD
#define PMBUS_CODE_RESERVED_50                    0xCE
#define PMBUS_CODE_RESERVED_51                    0xCF
#define PMBUS_CODE_MFR_SPECIFIC_00                0xD0
#define PMBUS_CODE_MFR_SPECIFIC_01                0xD1
#define PMBUS_CODE_MFR_SPECIFIC_02                0xD2
#define PMBUS_CODE_MFR_SPECIFIC_03                0xD3
#define PMBUS_CODE_MFR_SPECIFIC_04                0xD4
#define PMBUS_CODE_MFR_SPECIFIC_05                0xD5
#define PMBUS_CODE_MFR_SPECIFIC_06                0xD6
#define PMBUS_CODE_MFR_SPECIFIC_07                0xD7
#define PMBUS_CODE_MFR_SPECIFIC_08                0xD8
#define PMBUS_CODE_MFR_SPECIFIC_09                0xD9
#define PMBUS_CODE_MFR_SPECIFIC_10                0xDA
#define PMBUS_CODE_MFR_SPECIFIC_11                0xDB
#define PMBUS_CODE_MFR_SPECIFIC_12                0xDC
#define PMBUS_CODE_MFR_SPECIFIC_13                0xDD
#define PMBUS_CODE_MFR_SPECIFIC_14                0xDE
#define PMBUS_CODE_MFR_SPECIFIC_15                0xDF
#define PMBUS_CODE_MFR_SPECIFIC_16                0xE0
#define PMBUS_CODE_MFR_SPECIFIC_17                0xE1
#define PMBUS_CODE_MFR_SPECIFIC_18                0xE2
#define PMBUS_CODE_MFR_SPECIFIC_19                0xE3
#define PMBUS_CODE_MFR_SPECIFIC_20                0xE4
#define PMBUS_CODE_MFR_SPECIFIC_21                0xE5
#define PMBUS_CODE_MFR_SPECIFIC_22                0xE6
#define PMBUS_CODE_MFR_SPECIFIC_23                0xE7
#define PMBUS_CODE_MFR_SPECIFIC_24                0xE8
#define PMBUS_CODE_MFR_SPECIFIC_25                0xE9
#define PMBUS_CODE_MFR_SPECIFIC_26                0xEA
#define PMBUS_CODE_MFR_SPECIFIC_27                0xEB
#define PMBUS_CODE_MFR_SPECIFIC_28                0xEC
#define PMBUS_CODE_MFR_SPECIFIC_29                0xED
#define PMBUS_CODE_MFR_SPECIFIC_30                0xEE
#define PMBUS_CODE_MFR_SPECIFIC_31                0xEF
#define PMBUS_CODE_MFR_SPECIFIC_32                0xF0
#define PMBUS_CODE_MFR_SPECIFIC_33                0xF1
#define PMBUS_CODE_MFR_SPECIFIC_34                0xF2
#define PMBUS_CODE_MFR_SPECIFIC_35                0xF3
#define PMBUS_CODE_MFR_SPECIFIC_36                0xF4
#define PMBUS_CODE_MFR_SPECIFIC_37                0xF5
#define PMBUS_CODE_MFR_SPECIFIC_38                0xF6
#define PMBUS_CODE_MFR_SPECIFIC_39                0xF7
#define PMBUS_CODE_MFR_SPECIFIC_40                0xF8
#define PMBUS_CODE_MFR_SPECIFIC_41                0xF9
#define PMBUS_CODE_MFR_SPECIFIC_42                0xFA
#define PMBUS_CODE_MFR_SPECIFIC_43                0xFB
#define PMBUS_CODE_MFR_SPECIFIC_44                0xFC
#define PMBUS_CODE_MFR_SPECIFIC_45                0xFD
#define PMBUS_CODE_MFR_SPECIFIC_COMMAND_EXT       0xFE
#define PMBUS_CODE_PMBUS_COMMAND_EXT              0xFF


/*! @} End of pmbus_command_list */

#endif /* __PMBUS_CMD_H */
