
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_ahb0, 0);

    clock_add_to_group(clock_axif, 0);

    clock_add_to_group(clock_axis, 0);

    clock_add_to_group(clock_axic, 0);

    clock_add_to_group(clock_axin, 0);

    clock_add_to_group(clock_rom0, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_lmm1, 0);

    clock_add_to_group(clock_ram0, 0);

    clock_add_to_group(clock_ram1, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_xdma, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_ptpc, 0);

    clock_add_to_group(clock_qei0, 0);

    clock_add_to_group(clock_qei1, 0);

    clock_add_to_group(clock_qei2, 0);

    clock_add_to_group(clock_qei3, 0);

    clock_add_to_group(clock_qeo0, 0);

    clock_add_to_group(clock_qeo1, 0);

    clock_add_to_group(clock_qeo2, 0);

    clock_add_to_group(clock_qeo3, 0);

    clock_add_to_group(clock_pwm0, 0);

    clock_add_to_group(clock_pwm1, 0);

    clock_add_to_group(clock_pwm2, 0);

    clock_add_to_group(clock_pwm3, 0);

    clock_add_to_group(clock_rdc0, 0);

    clock_add_to_group(clock_rdc1, 0);

    clock_add_to_group(clock_plb0, 0);

    clock_add_to_group(clock_sei0, 0);

    clock_add_to_group(clock_mtg0, 0);

    clock_add_to_group(clock_mtg1, 0);

    clock_add_to_group(clock_vsc0, 0);

    clock_add_to_group(clock_vsc1, 0);

    clock_add_to_group(clock_clc0, 0);

    clock_add_to_group(clock_clc1, 0);

    clock_add_to_group(clock_emds, 0);
}

void init_board_cpu1_clock(void)
{
    clock_add_to_group(clock_cpu1, 1);

    clock_add_to_group(clock_mchtmr1, 1);
}

void init_board_clock_source(void)
{
    /* Generate clk_top_cpu0 code */
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 1);

    /* Generate clk_top_cpu1 code */
    clock_set_source_divider(clock_cpu1, clk_src_pll0_clk0, 1);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);

    /* Generate clk_top_mct1 code */
    clock_set_source_divider(clock_mchtmr1, clk_src_osc24m, 1);
}

void init_femc_clock(void)
{
    clock_add_to_group(clock_femc, 0);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart1_clock(void)
{
    clock_add_to_group(clock_uart1, 0);
}

void init_uart2_clock(void)
{
    clock_add_to_group(clock_uart2, 0);
}

void init_uart6_clock(void)
{
    clock_add_to_group(clock_uart6, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_i2c3_clock(void)
{
    clock_add_to_group(clock_i2c3, 0);
}

void init_i2c4_clock(void)
{
    clock_add_to_group(clock_i2c4, 0);
}

void init_i2c5_clock(void)
{
    clock_add_to_group(clock_i2c5, 0);
}

void init_i2c6_clock(void)
{
    clock_add_to_group(clock_i2c6, 0);
}

void init_i2c7_clock(void)
{
    clock_add_to_group(clock_i2c7, 0);
}

void init_i2c_eeprom_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_spi1_clock(void)
{
    clock_add_to_group(clock_spi1, 0);
}

void init_spi3_clock(void)
{
    clock_add_to_group(clock_spi3, 0);
}

void init_spi6_clock(void)
{
    clock_add_to_group(clock_spi6, 0);
}

void init_spi7_clock(void)
{
    clock_add_to_group(clock_spi7, 0);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_dao_clock(void)
{
    clock_add_to_group(clock_dao, 0);
}

void init_pdm_clock(void)
{
    clock_add_to_group(clock_pdm, 0);
}

void init_i2s0_clock_group(void)
{
    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s0_clock_source_22050(void)
{
    /* Generate clk_top_aud0 code */
    clock_set_source_divider(clock_aud0, clk_src_pll1_clk0, 71);
}

void init_i2s0_clock_source_default(void)
{
    /* Generate clk_top_aud0 code */
    clock_set_source_divider(clock_aud0, clk_src_pll2_clk0, 21);
}

void init_i2s0_clock_i2s_source(void)
{
    /* Generate clk_top_i2s0 code */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll2_clk0, 21);
}

void init_i2s1_clock_group(void)
{
    clock_add_to_group(clock_i2s1, 0);
}

void init_i2s1_clock_source_22050(void)
{
    /* Generate clk_top_aud1 code */
    clock_set_source_divider(clock_aud1, clk_src_pll1_clk0, 71);
}

void init_i2s1_clock_source_default(void)
{
    /* Generate clk_top_aud1 code */
    clock_set_source_divider(clock_aud1, clk_src_pll2_clk0, 21);
}

void init_i2s1_clock_i2s_source(void)
{
    /* Generate clk_top_i2s1 code */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll2_clk0, 21);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /*
     * Generate clk_top_adc0 code
     * Generate clk_top_ana0 code
     */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc1_bus_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc1_analog_clock(void)
{
    /* Generate clk_top_adc1 code */
    clock_set_adc_source(clock_adc1, clk_adc_src_ana1);
    clock_set_source_divider(clock_ana1, clk_src_pll1_clk0, 4);

    /* Generate clk_top_ana0 code */
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc1, 0);
}

void init_adc2_bus_clock(void)
{
    /* Generate clk_top_adc2 code */
    clock_set_adc_source(clock_adc2, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc2_analog_clock(void)
{
    /* Generate clk_top_adc2 code */
    clock_set_adc_source(clock_adc2, clk_adc_src_ana2);
    clock_set_source_divider(clock_ana2, clk_src_pll1_clk0, 4);

    /* Generate clk_top_ana0 code */
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc2, 0);
}

void init_adc3_bus_clock(void)
{
    /* Generate clk_top_adc3 code */
    clock_set_adc_source(clock_adc3, clk_adc_src_ahb0);
    clock_set_source_divider(clock_ahb0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc3, 0);
}

void init_adc3_analog_clock(void)
{
    /* Generate clk_top_adc3 code */
    clock_set_adc_source(clock_adc3, clk_adc_src_ana3);
    clock_set_source_divider(clock_ana3, clk_src_pll1_clk0, 4);

    /* Generate clk_top_ana0 code */
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc3, 0);
}

void init_acmp0_clock(void)
{
    clock_add_to_group(clock_acmp0, 0);
}

void init_acmp0_clock_group1(void)
{
    clock_add_to_group(clock_acmp0, 1);
}

void init_can0_clock(void)
{
    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can0, 0);
}

void init_can1_clock(void)
{
    /* Generate clk_top_can1 code */
    clock_set_source_divider(clock_can1, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can1, 0);
}

void init_can2_clock(void)
{
    /* Generate clk_top_can2 code */
    clock_set_source_divider(clock_can2, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can2, 0);
}

void init_can3_clock(void)
{
    /* Generate clk_top_can3 code */
    clock_set_source_divider(clock_can3, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can3, 0);
}

void init_can4_clock(void)
{
    /* Generate clk_top_can4 code */
    clock_set_source_divider(clock_can4, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can4, 0);
}

void init_can5_clock(void)
{
    /* Generate clk_top_can5 code */
    clock_set_source_divider(clock_can5, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can5, 0);
}

void init_can6_clock(void)
{
    /* Generate clk_top_can6 code */
    clock_set_source_divider(clock_can6, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can6, 0);
}

void init_can7_clock(void)
{
    /* Generate clk_top_can7 code */
    clock_set_source_divider(clock_can7, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can7, 0);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr0_clock_group1(void)
{
    clock_add_to_group(clock_gptmr0, 1);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_gptmr1_clock_group1(void)
{
    clock_add_to_group(clock_gptmr1, 1);
}

void init_gptmr2_clock(void)
{
    clock_add_to_group(clock_gptmr2, 0);
}

void init_gptmr2_clock_group1(void)
{
    clock_add_to_group(clock_gptmr2, 1);
}

void init_gptmr3_clock(void)
{
    clock_add_to_group(clock_gptmr3, 0);
}

void init_gptmr3_clock_group1(void)
{
    clock_add_to_group(clock_gptmr3, 1);
}

void init_gptmr4_clock(void)
{
    clock_add_to_group(clock_gptmr4, 0);
}

void init_gptmr4_clock_group1(void)
{
    clock_add_to_group(clock_gptmr4, 1);
}

void init_gptmr5_clock(void)
{
    clock_add_to_group(clock_gptmr5, 0);
}

void init_gptmr5_clock_group1(void)
{
    clock_add_to_group(clock_gptmr5, 1);
}

void init_gptmr6_clock(void)
{
    clock_add_to_group(clock_gptmr6, 0);
}

void init_gptmr6_clock_group1(void)
{
    clock_add_to_group(clock_gptmr6, 1);
}

void init_gptmr7_clock(void)
{
    clock_add_to_group(clock_gptmr7, 0);
}

void init_gptmr7_clock_group1(void)
{
    clock_add_to_group(clock_gptmr7, 1);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_ptmr_clock_group1(void)
{
    clock_add_to_group(clock_ptmr, 1);
}

void init_enet_ptp_clock(void)
{
    clock_add_to_group(clock_ptp0, 0);
}

void init_enet_ptp_clock_group1(void)
{
    clock_add_to_group(clock_ptp0, 1);
}

void init_enet_rgmii_clock(void)
{
    clock_add_to_group(clock_eth0, 0);
}

void init_enet_rgmii_clock_group1(void)
{
    clock_add_to_group(clock_eth0, 1);
}

void init_esc0_clock(void)
{
    clock_add_to_group(clock_esc0, 0);
}

void init_tsw_smi_clock(void)
{
    clock_add_to_group(clock_esc0, 0);

    clock_add_to_group(clock_eth0, 0);
}

void init_tsw_smi_clock_group1(void)
{
    clock_add_to_group(clock_esc0, 1);

    clock_add_to_group(clock_eth0, 1);
}

void init_tsw_clock(void)
{
    clock_add_to_group(clock_tsn1, 0);

    clock_add_to_group(clock_tsn2, 0);

    clock_add_to_group(clock_tsn3, 0);

    clock_add_to_group(clock_esc0, 0);
}
