/*
 * Copyright (c) 2021-2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */


#ifndef HPM_MTGV2_H
#define HPM_MTGV2_H

typedef struct {
    struct {
        __RW uint32_t CONTROL;                 /* 0x0: tra_control */
        __RW uint32_t SHIFT;                   /* 0x4: tra_shift */
        __RW uint32_t LINK;                    /* 0x8: tra_link */
        __R  uint8_t  RESERVED0[20];           /* 0xC - 0x1F: Reserved */
        struct {
            __RW uint32_t CONTROL;             /* 0x20: tra_cmd_control */
            __RW uint32_t REV_PRESET;          /* 0x24: tra_cmd_rev_preset */
            __RW uint32_t POS_PRESET;          /* 0x28: tra_cmd_pos_preset */
            __RW uint32_t VEL_PRESET;          /* 0x2C: tra_cmd_vel_preset */
            __RW uint32_t ACC_PRESET;          /* 0x30: tra_cmd_acc_preset */
            __RW uint32_t JER_PRESET;          /* 0x34: tra_cmd_jer_preset */
            __R  uint32_t TIMESTAMP;           /* 0x38: tra_cmd_timestamp */
            __R  uint8_t  RESERVED0[4];        /* 0x3C - 0x3F: Reserved */
        } CMD[4];
        __R  uint32_t LOCK_REV;                /* 0xA0: tra_lock_rev */
        __R  uint32_t LOCK_POS;                /* 0xA4: tra_lock_pos */
        __R  uint32_t LOCK_VEL;                /* 0xA8: tra_lock_vel */
        __R  uint32_t LOCK_ACC;                /* 0xAC: tra_lock_acc */
        __R  uint32_t LOCK_TIME;               /* 0xB0: tra_lock_time */
        __R  uint8_t  RESERVED1[12];           /* 0xB4 - 0xBF: Reserved */
        __RW uint32_t STEP_LIMIT_CTRL;         /* 0xC0: tra_step_limit_ctrl */
        __RW uint32_t VEL_STEP_MAX;            /* 0xC4: tra_vel_step_max */
        __RW uint32_t VEL_STEP_MIN;            /* 0xC8: tra_vel_step_min */
        __RW uint32_t POS_STEP_MAX;            /* 0xCC: tra_pos_step_max */
        __RW uint32_t POS_STEP_MIN;            /* 0xD0: tra_pos_step_min */
        __RW uint32_t VEL_LIMIT_P;             /* 0xD4: tra_vel_limit_p */
        __RW uint32_t VEL_LIMIT_N;             /* 0xD8: tra_vel_limit_n */
        __R  uint8_t  RESERVED2[3876];         /* 0xDC - 0xFFF: Reserved */
    } TRA[2];
    struct {
        __RW uint32_t CONTROL;                 /* 0x2000: event_control */
        __RW uint32_t PRESET_0;                /* 0x2004: event_preset_0 */
        __RW uint32_t PRESET_1;                /* 0x2008: event_preset_1 */
        __RW uint32_t PRESET_2;                /* 0x200C: event_preset_2 */
        __RW uint32_t PRESET_3;                /* 0x2010: event_preset_3 */
        __R  uint32_t TIMESTAMP;               /* 0x2014: event_timestamp */
        __R  uint8_t  RESERVED0[8];            /* 0x2018 - 0x201F: Reserved */
    } EVENT[4];
    __RW uint32_t SW_EVENT;                    /* 0x2080: sw_event */
    __W  uint32_t SW_GLB_RESET;                /* 0x2084: sw_glb_reset */
    __RW uint32_t IRQ_ENABLE;                  /* 0x2088: irq_enable */
    __W  uint32_t IRQ_STATUS;                  /* 0x208C: irq_status */
    __R  uint8_t  RESERVED0[3952];             /* 0x2090 - 0x2FFF: Reserved */
    __RW uint32_t FILTER_CONTROL;              /* 0x3000: filter_control */
    __R  uint8_t  RESERVED1[20];               /* 0x3004 - 0x3017: Reserved */
    __RW uint32_t FILTER_VEL_FF;               /* 0x3018: filter_vel_ff */
    __RW uint32_t FILTER_ACC_FF;               /* 0x301C: filter_acc_ff */
    __R  uint8_t  RESERVED2[8];                /* 0x3020 - 0x3027: Reserved */
    __RW uint32_t FILTER_TIME_CONSTANT_TP;     /* 0x3028: filter_time_constant_tp */
    __RW uint32_t FILTER_TIME_CONSTANT_TZ;     /* 0x302C: filter_time_constant_tz */
    __RW uint32_t FILTER_TIME_CONSTANT_TZ_1;   /* 0x3030: filter_time_constant_tz_1 */
    __R  uint8_t  RESERVED3[4];                /* 0x3034 - 0x3037: Reserved */
    __RW uint32_t FILTER_GAIN;                 /* 0x3038: filter_gain */
    __RW uint32_t FILTER_STAGE_SHIFT0;         /* 0x303C: filter_stage_shift0 */
    __RW uint32_t FILTER_STAGE_SHIFT1;         /* 0x3040: filter_stage_shift1 */
    __RW uint32_t FILTER_PARAM_SHIFT;          /* 0x3044: filter_param_shift */
    __RW uint32_t FILTER_TIME_SHIFT;           /* 0x3048: filter_time_shift */
    __RW uint32_t FILTER_FF_SHIFT;             /* 0x304C: filter_ff_shift */
    __RW uint32_t FILTER_TIME1_SW_ADJUST;      /* 0x3050: filter_time1_sw_adjust */
    __RW uint32_t FILTER_TIME0_SW_ADJUST;      /* 0x3054: filter_time0_sw_adjust */
    __R  uint8_t  RESERVED4[20];               /* 0x3058 - 0x306B: Reserved */
    __RW uint32_t FILTER_TIMEOUT_CNT;          /* 0x306C: filter_timeout_cnt */
    __R  uint32_t FILTER_REV_LOCK;             /* 0x3070: filter_rev_lock */
    __R  uint32_t FILTER_POS_LOCK;             /* 0x3074: filter_pos_lock */
    __R  uint32_t FILTER_VEL_LOCK;             /* 0x3078: filter_vel_lock */
    __R  uint32_t FILTER_ACC_LOCK;             /* 0x307C: filter_acc_lock */
} MTGV2_Type;


/* Bitfield definition for register of struct array TRA: CONTROL */
/*
 * SW_LOCK (RW)
 *
 */
#define MTGV2_TRA_CONTROL_SW_LOCK_MASK (0x2U)
#define MTGV2_TRA_CONTROL_SW_LOCK_SHIFT (1U)
#define MTGV2_TRA_CONTROL_SW_LOCK_SET(x) (((uint32_t)(x) << MTGV2_TRA_CONTROL_SW_LOCK_SHIFT) & MTGV2_TRA_CONTROL_SW_LOCK_MASK)
#define MTGV2_TRA_CONTROL_SW_LOCK_GET(x) (((uint32_t)(x) & MTGV2_TRA_CONTROL_SW_LOCK_MASK) >> MTGV2_TRA_CONTROL_SW_LOCK_SHIFT)

/*
 * OVALID_CLEAR (WO)
 *
 */
#define MTGV2_TRA_CONTROL_OVALID_CLEAR_MASK (0x1U)
#define MTGV2_TRA_CONTROL_OVALID_CLEAR_SHIFT (0U)
#define MTGV2_TRA_CONTROL_OVALID_CLEAR_SET(x) (((uint32_t)(x) << MTGV2_TRA_CONTROL_OVALID_CLEAR_SHIFT) & MTGV2_TRA_CONTROL_OVALID_CLEAR_MASK)
#define MTGV2_TRA_CONTROL_OVALID_CLEAR_GET(x) (((uint32_t)(x) & MTGV2_TRA_CONTROL_OVALID_CLEAR_MASK) >> MTGV2_TRA_CONTROL_OVALID_CLEAR_SHIFT)

/* Bitfield definition for register of struct array TRA: SHIFT */
/*
 * JER_SHIFT (RW)
 *
 */
#define MTGV2_TRA_SHIFT_JER_SHIFT_MASK (0x700U)
#define MTGV2_TRA_SHIFT_JER_SHIFT_SHIFT (8U)
#define MTGV2_TRA_SHIFT_JER_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_TRA_SHIFT_JER_SHIFT_SHIFT) & MTGV2_TRA_SHIFT_JER_SHIFT_MASK)
#define MTGV2_TRA_SHIFT_JER_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_TRA_SHIFT_JER_SHIFT_MASK) >> MTGV2_TRA_SHIFT_JER_SHIFT_SHIFT)

/*
 * ACC_SHIFT (RW)
 *
 */
#define MTGV2_TRA_SHIFT_ACC_SHIFT_MASK (0x70U)
#define MTGV2_TRA_SHIFT_ACC_SHIFT_SHIFT (4U)
#define MTGV2_TRA_SHIFT_ACC_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_TRA_SHIFT_ACC_SHIFT_SHIFT) & MTGV2_TRA_SHIFT_ACC_SHIFT_MASK)
#define MTGV2_TRA_SHIFT_ACC_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_TRA_SHIFT_ACC_SHIFT_MASK) >> MTGV2_TRA_SHIFT_ACC_SHIFT_SHIFT)

/*
 * VEL_SHIFT (RW)
 *
 */
#define MTGV2_TRA_SHIFT_VEL_SHIFT_MASK (0xFU)
#define MTGV2_TRA_SHIFT_VEL_SHIFT_SHIFT (0U)
#define MTGV2_TRA_SHIFT_VEL_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_TRA_SHIFT_VEL_SHIFT_SHIFT) & MTGV2_TRA_SHIFT_VEL_SHIFT_MASK)
#define MTGV2_TRA_SHIFT_VEL_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_TRA_SHIFT_VEL_SHIFT_MASK) >> MTGV2_TRA_SHIFT_VEL_SHIFT_SHIFT)

/* Bitfield definition for register of struct array TRA: LINK */
/*
 * LINK_CFG_3 (RW)
 *
 */
#define MTGV2_TRA_LINK_LINK_CFG_3_MASK (0x7000U)
#define MTGV2_TRA_LINK_LINK_CFG_3_SHIFT (12U)
#define MTGV2_TRA_LINK_LINK_CFG_3_SET(x) (((uint32_t)(x) << MTGV2_TRA_LINK_LINK_CFG_3_SHIFT) & MTGV2_TRA_LINK_LINK_CFG_3_MASK)
#define MTGV2_TRA_LINK_LINK_CFG_3_GET(x) (((uint32_t)(x) & MTGV2_TRA_LINK_LINK_CFG_3_MASK) >> MTGV2_TRA_LINK_LINK_CFG_3_SHIFT)

/*
 * LINK_CFG_2 (RW)
 *
 */
#define MTGV2_TRA_LINK_LINK_CFG_2_MASK (0x700U)
#define MTGV2_TRA_LINK_LINK_CFG_2_SHIFT (8U)
#define MTGV2_TRA_LINK_LINK_CFG_2_SET(x) (((uint32_t)(x) << MTGV2_TRA_LINK_LINK_CFG_2_SHIFT) & MTGV2_TRA_LINK_LINK_CFG_2_MASK)
#define MTGV2_TRA_LINK_LINK_CFG_2_GET(x) (((uint32_t)(x) & MTGV2_TRA_LINK_LINK_CFG_2_MASK) >> MTGV2_TRA_LINK_LINK_CFG_2_SHIFT)

/*
 * LINK_CFG_1 (RW)
 *
 */
#define MTGV2_TRA_LINK_LINK_CFG_1_MASK (0x70U)
#define MTGV2_TRA_LINK_LINK_CFG_1_SHIFT (4U)
#define MTGV2_TRA_LINK_LINK_CFG_1_SET(x) (((uint32_t)(x) << MTGV2_TRA_LINK_LINK_CFG_1_SHIFT) & MTGV2_TRA_LINK_LINK_CFG_1_MASK)
#define MTGV2_TRA_LINK_LINK_CFG_1_GET(x) (((uint32_t)(x) & MTGV2_TRA_LINK_LINK_CFG_1_MASK) >> MTGV2_TRA_LINK_LINK_CFG_1_SHIFT)

/*
 * LINK_CFG_0 (RW)
 *
 */
#define MTGV2_TRA_LINK_LINK_CFG_0_MASK (0x7U)
#define MTGV2_TRA_LINK_LINK_CFG_0_SHIFT (0U)
#define MTGV2_TRA_LINK_LINK_CFG_0_SET(x) (((uint32_t)(x) << MTGV2_TRA_LINK_LINK_CFG_0_SHIFT) & MTGV2_TRA_LINK_LINK_CFG_0_MASK)
#define MTGV2_TRA_LINK_LINK_CFG_0_GET(x) (((uint32_t)(x) & MTGV2_TRA_LINK_LINK_CFG_0_MASK) >> MTGV2_TRA_LINK_LINK_CFG_0_SHIFT)

/* Bitfield definition for register of struct array TRA: CONTROL */
/*
 * MODE (RW)
 *
 */
#define MTGV2_TRA_CMD_CONTROL_MODE_MASK (0x20000000UL)
#define MTGV2_TRA_CMD_CONTROL_MODE_SHIFT (29U)
#define MTGV2_TRA_CMD_CONTROL_MODE_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_CONTROL_MODE_SHIFT) & MTGV2_TRA_CMD_CONTROL_MODE_MASK)
#define MTGV2_TRA_CMD_CONTROL_MODE_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_CONTROL_MODE_MASK) >> MTGV2_TRA_CMD_CONTROL_MODE_SHIFT)

/*
 * OBJECT (RW)
 *
 */
#define MTGV2_TRA_CMD_CONTROL_OBJECT_MASK (0x1FU)
#define MTGV2_TRA_CMD_CONTROL_OBJECT_SHIFT (0U)
#define MTGV2_TRA_CMD_CONTROL_OBJECT_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_CONTROL_OBJECT_SHIFT) & MTGV2_TRA_CMD_CONTROL_OBJECT_MASK)
#define MTGV2_TRA_CMD_CONTROL_OBJECT_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_CONTROL_OBJECT_MASK) >> MTGV2_TRA_CMD_CONTROL_OBJECT_SHIFT)

/* Bitfield definition for register of struct array TRA: REV_PRESET */
/*
 * REV_PRESET (RW)
 *
 */
#define MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_SHIFT (0U)
#define MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_SHIFT) & MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_MASK)
#define MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_MASK) >> MTGV2_TRA_CMD_REV_PRESET_REV_PRESET_SHIFT)

/* Bitfield definition for register of struct array TRA: POS_PRESET */
/*
 * POS_PRESET (RW)
 *
 */
#define MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_SHIFT (0U)
#define MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_SHIFT) & MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_MASK)
#define MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_MASK) >> MTGV2_TRA_CMD_POS_PRESET_POS_PRESET_SHIFT)

/* Bitfield definition for register of struct array TRA: VEL_PRESET */
/*
 * VEL_PRESET (RW)
 *
 */
#define MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_SHIFT (0U)
#define MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_SHIFT) & MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_MASK)
#define MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_MASK) >> MTGV2_TRA_CMD_VEL_PRESET_VEL_PRESET_SHIFT)

/* Bitfield definition for register of struct array TRA: ACC_PRESET */
/*
 * ACC_PRESET (RW)
 *
 */
#define MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_SHIFT (0U)
#define MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_SHIFT) & MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_MASK)
#define MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_MASK) >> MTGV2_TRA_CMD_ACC_PRESET_ACC_PRESET_SHIFT)

/* Bitfield definition for register of struct array TRA: JER_PRESET */
/*
 * JER_PRESET (RW)
 *
 */
#define MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_SHIFT (0U)
#define MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_SET(x) (((uint32_t)(x) << MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_SHIFT) & MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_MASK)
#define MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_MASK) >> MTGV2_TRA_CMD_JER_PRESET_JER_PRESET_SHIFT)

/* Bitfield definition for register of struct array TRA: TIMESTAMP */
/*
 * TIMESTAMP (RO)
 *
 */
#define MTGV2_TRA_CMD_TIMESTAMP_TIMESTAMP_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_CMD_TIMESTAMP_TIMESTAMP_SHIFT (0U)
#define MTGV2_TRA_CMD_TIMESTAMP_TIMESTAMP_GET(x) (((uint32_t)(x) & MTGV2_TRA_CMD_TIMESTAMP_TIMESTAMP_MASK) >> MTGV2_TRA_CMD_TIMESTAMP_TIMESTAMP_SHIFT)

/* Bitfield definition for register of struct array TRA: LOCK_REV */
/*
 * LOCK_REV (RO)
 *
 */
#define MTGV2_TRA_LOCK_REV_LOCK_REV_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_LOCK_REV_LOCK_REV_SHIFT (0U)
#define MTGV2_TRA_LOCK_REV_LOCK_REV_GET(x) (((uint32_t)(x) & MTGV2_TRA_LOCK_REV_LOCK_REV_MASK) >> MTGV2_TRA_LOCK_REV_LOCK_REV_SHIFT)

/* Bitfield definition for register of struct array TRA: LOCK_POS */
/*
 * LOCK_POS (RO)
 *
 */
#define MTGV2_TRA_LOCK_POS_LOCK_POS_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_LOCK_POS_LOCK_POS_SHIFT (0U)
#define MTGV2_TRA_LOCK_POS_LOCK_POS_GET(x) (((uint32_t)(x) & MTGV2_TRA_LOCK_POS_LOCK_POS_MASK) >> MTGV2_TRA_LOCK_POS_LOCK_POS_SHIFT)

/* Bitfield definition for register of struct array TRA: LOCK_VEL */
/*
 * LOCK_VEL (RO)
 *
 */
#define MTGV2_TRA_LOCK_VEL_LOCK_VEL_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_LOCK_VEL_LOCK_VEL_SHIFT (0U)
#define MTGV2_TRA_LOCK_VEL_LOCK_VEL_GET(x) (((uint32_t)(x) & MTGV2_TRA_LOCK_VEL_LOCK_VEL_MASK) >> MTGV2_TRA_LOCK_VEL_LOCK_VEL_SHIFT)

/* Bitfield definition for register of struct array TRA: LOCK_ACC */
/*
 * LOCK_ACC (RO)
 *
 */
#define MTGV2_TRA_LOCK_ACC_LOCK_ACC_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_LOCK_ACC_LOCK_ACC_SHIFT (0U)
#define MTGV2_TRA_LOCK_ACC_LOCK_ACC_GET(x) (((uint32_t)(x) & MTGV2_TRA_LOCK_ACC_LOCK_ACC_MASK) >> MTGV2_TRA_LOCK_ACC_LOCK_ACC_SHIFT)

/* Bitfield definition for register of struct array TRA: LOCK_TIME */
/*
 * LOCK_TIME (RO)
 *
 */
#define MTGV2_TRA_LOCK_TIME_LOCK_TIME_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_LOCK_TIME_LOCK_TIME_SHIFT (0U)
#define MTGV2_TRA_LOCK_TIME_LOCK_TIME_GET(x) (((uint32_t)(x) & MTGV2_TRA_LOCK_TIME_LOCK_TIME_MASK) >> MTGV2_TRA_LOCK_TIME_LOCK_TIME_SHIFT)

/* Bitfield definition for register of struct array TRA: STEP_LIMIT_CTRL */
/*
 * POS_ONE_WAY_FORCE_MODE (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_MASK (0x1000U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_SHIFT (12U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_FORCE_MODE_SHIFT)

/*
 * POS_ONE_WAY_MODE (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_MASK (0x800U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_SHIFT (11U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_MODE_SHIFT)

/*
 * POS_ONE_WAY_EN (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_MASK (0x400U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_SHIFT (10U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_POS_ONE_WAY_EN_SHIFT)

/*
 * POS_STEP_MODE (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_MASK (0x200U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_SHIFT (9U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_MODE_SHIFT)

/*
 * POS_STEP_EN (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_MASK (0x100U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_SHIFT (8U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_POS_STEP_EN_SHIFT)

/*
 * VEL_ONE_WAY_MODE (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_MASK (0x4U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_SHIFT (2U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_MODE_SHIFT)

/*
 * VEL_ONE_WAY_EN (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_MASK (0x2U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_SHIFT (1U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_VEL_ONE_WAY_EN_SHIFT)

/*
 * VEL_STEP_EN (RW)
 *
 */
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_MASK (0x1U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_SHIFT (0U)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_SET(x) (((uint32_t)(x) << MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_SHIFT) & MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_MASK)
#define MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_GET(x) (((uint32_t)(x) & MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_MASK) >> MTGV2_TRA_STEP_LIMIT_CTRL_VEL_STEP_EN_SHIFT)

/* Bitfield definition for register of struct array TRA: VEL_STEP_MAX */
/*
 * VEL_STEP_MAX (RW)
 *
 */
#define MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_SHIFT (0U)
#define MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_SET(x) (((uint32_t)(x) << MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_SHIFT) & MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_MASK)
#define MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_GET(x) (((uint32_t)(x) & MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_MASK) >> MTGV2_TRA_VEL_STEP_MAX_VEL_STEP_MAX_SHIFT)

/* Bitfield definition for register of struct array TRA: VEL_STEP_MIN */
/*
 * VEL_STEP_MIN (RW)
 *
 */
#define MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_SHIFT (0U)
#define MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_SET(x) (((uint32_t)(x) << MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_SHIFT) & MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_MASK)
#define MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_GET(x) (((uint32_t)(x) & MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_MASK) >> MTGV2_TRA_VEL_STEP_MIN_VEL_STEP_MIN_SHIFT)

/* Bitfield definition for register of struct array TRA: POS_STEP_MAX */
/*
 * POS_STEP_MAX (RW)
 *
 */
#define MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_SHIFT (0U)
#define MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_SET(x) (((uint32_t)(x) << MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_SHIFT) & MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_MASK)
#define MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_GET(x) (((uint32_t)(x) & MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_MASK) >> MTGV2_TRA_POS_STEP_MAX_POS_STEP_MAX_SHIFT)

/* Bitfield definition for register of struct array TRA: POS_STEP_MIN */
/*
 * POS_STEP_MIN (RW)
 *
 */
#define MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_SHIFT (0U)
#define MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_SET(x) (((uint32_t)(x) << MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_SHIFT) & MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_MASK)
#define MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_GET(x) (((uint32_t)(x) & MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_MASK) >> MTGV2_TRA_POS_STEP_MIN_POS_STEP_MIN_SHIFT)

/* Bitfield definition for register of struct array TRA: VEL_LIMIT_P */
/*
 * VEL_LIMIT_P (RW)
 *
 */
#define MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_SHIFT (0U)
#define MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_SET(x) (((uint32_t)(x) << MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_SHIFT) & MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_MASK)
#define MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_GET(x) (((uint32_t)(x) & MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_MASK) >> MTGV2_TRA_VEL_LIMIT_P_VEL_LIMIT_P_SHIFT)

/* Bitfield definition for register of struct array TRA: VEL_LIMIT_N */
/*
 * VEL_LIMIT_N (RW)
 *
 */
#define MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_MASK (0xFFFFFFFFUL)
#define MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_SHIFT (0U)
#define MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_SET(x) (((uint32_t)(x) << MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_SHIFT) & MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_MASK)
#define MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_GET(x) (((uint32_t)(x) & MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_MASK) >> MTGV2_TRA_VEL_LIMIT_N_VEL_LIMIT_N_SHIFT)

/* Bitfield definition for register of struct array EVENT: CONTROL */
/*
 * ENABLE (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_ENABLE_MASK (0x80000000UL)
#define MTGV2_EVENT_CONTROL_ENABLE_SHIFT (31U)
#define MTGV2_EVENT_CONTROL_ENABLE_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_ENABLE_SHIFT) & MTGV2_EVENT_CONTROL_ENABLE_MASK)
#define MTGV2_EVENT_CONTROL_ENABLE_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_ENABLE_MASK) >> MTGV2_EVENT_CONTROL_ENABLE_SHIFT)

/*
 * SOURCE_MUX (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_SOURCE_MUX_MASK (0x7C000000UL)
#define MTGV2_EVENT_CONTROL_SOURCE_MUX_SHIFT (26U)
#define MTGV2_EVENT_CONTROL_SOURCE_MUX_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_SOURCE_MUX_SHIFT) & MTGV2_EVENT_CONTROL_SOURCE_MUX_MASK)
#define MTGV2_EVENT_CONTROL_SOURCE_MUX_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_SOURCE_MUX_MASK) >> MTGV2_EVENT_CONTROL_SOURCE_MUX_SHIFT)

/*
 * OBJECT (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_OBJECT_MASK (0x3C00000UL)
#define MTGV2_EVENT_CONTROL_OBJECT_SHIFT (22U)
#define MTGV2_EVENT_CONTROL_OBJECT_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_OBJECT_SHIFT) & MTGV2_EVENT_CONTROL_OBJECT_MASK)
#define MTGV2_EVENT_CONTROL_OBJECT_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_OBJECT_MASK) >> MTGV2_EVENT_CONTROL_OBJECT_SHIFT)

/*
 * MODE (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_MODE_MASK (0x3C0000UL)
#define MTGV2_EVENT_CONTROL_MODE_SHIFT (18U)
#define MTGV2_EVENT_CONTROL_MODE_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_MODE_SHIFT) & MTGV2_EVENT_CONTROL_MODE_MASK)
#define MTGV2_EVENT_CONTROL_MODE_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_MODE_MASK) >> MTGV2_EVENT_CONTROL_MODE_SHIFT)

/*
 * DIR (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_DIR_MASK (0x30000UL)
#define MTGV2_EVENT_CONTROL_DIR_SHIFT (16U)
#define MTGV2_EVENT_CONTROL_DIR_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_DIR_SHIFT) & MTGV2_EVENT_CONTROL_DIR_MASK)
#define MTGV2_EVENT_CONTROL_DIR_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_DIR_MASK) >> MTGV2_EVENT_CONTROL_DIR_SHIFT)

/*
 * DIR_MODE (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_DIR_MODE_MASK (0x8000U)
#define MTGV2_EVENT_CONTROL_DIR_MODE_SHIFT (15U)
#define MTGV2_EVENT_CONTROL_DIR_MODE_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_DIR_MODE_SHIFT) & MTGV2_EVENT_CONTROL_DIR_MODE_MASK)
#define MTGV2_EVENT_CONTROL_DIR_MODE_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_DIR_MODE_MASK) >> MTGV2_EVENT_CONTROL_DIR_MODE_SHIFT)

/*
 * CMP_MODE (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_CMP_MODE_MASK (0x4000U)
#define MTGV2_EVENT_CONTROL_CMP_MODE_SHIFT (14U)
#define MTGV2_EVENT_CONTROL_CMP_MODE_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_CMP_MODE_SHIFT) & MTGV2_EVENT_CONTROL_CMP_MODE_MASK)
#define MTGV2_EVENT_CONTROL_CMP_MODE_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_CMP_MODE_MASK) >> MTGV2_EVENT_CONTROL_CMP_MODE_SHIFT)

/*
 * TRIG_NUM (RW)
 *
 */
#define MTGV2_EVENT_CONTROL_TRIG_NUM_MASK (0x2000U)
#define MTGV2_EVENT_CONTROL_TRIG_NUM_SHIFT (13U)
#define MTGV2_EVENT_CONTROL_TRIG_NUM_SET(x) (((uint32_t)(x) << MTGV2_EVENT_CONTROL_TRIG_NUM_SHIFT) & MTGV2_EVENT_CONTROL_TRIG_NUM_MASK)
#define MTGV2_EVENT_CONTROL_TRIG_NUM_GET(x) (((uint32_t)(x) & MTGV2_EVENT_CONTROL_TRIG_NUM_MASK) >> MTGV2_EVENT_CONTROL_TRIG_NUM_SHIFT)

/* Bitfield definition for register of struct array EVENT: PRESET_0 */
/*
 * PRESET (RW)
 *
 */
#define MTGV2_EVENT_PRESET_0_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_EVENT_PRESET_0_PRESET_SHIFT (0U)
#define MTGV2_EVENT_PRESET_0_PRESET_SET(x) (((uint32_t)(x) << MTGV2_EVENT_PRESET_0_PRESET_SHIFT) & MTGV2_EVENT_PRESET_0_PRESET_MASK)
#define MTGV2_EVENT_PRESET_0_PRESET_GET(x) (((uint32_t)(x) & MTGV2_EVENT_PRESET_0_PRESET_MASK) >> MTGV2_EVENT_PRESET_0_PRESET_SHIFT)

/* Bitfield definition for register of struct array EVENT: PRESET_1 */
/*
 * PRESET (RW)
 *
 */
#define MTGV2_EVENT_PRESET_1_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_EVENT_PRESET_1_PRESET_SHIFT (0U)
#define MTGV2_EVENT_PRESET_1_PRESET_SET(x) (((uint32_t)(x) << MTGV2_EVENT_PRESET_1_PRESET_SHIFT) & MTGV2_EVENT_PRESET_1_PRESET_MASK)
#define MTGV2_EVENT_PRESET_1_PRESET_GET(x) (((uint32_t)(x) & MTGV2_EVENT_PRESET_1_PRESET_MASK) >> MTGV2_EVENT_PRESET_1_PRESET_SHIFT)

/* Bitfield definition for register of struct array EVENT: PRESET_2 */
/*
 * PRESET (RW)
 *
 */
#define MTGV2_EVENT_PRESET_2_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_EVENT_PRESET_2_PRESET_SHIFT (0U)
#define MTGV2_EVENT_PRESET_2_PRESET_SET(x) (((uint32_t)(x) << MTGV2_EVENT_PRESET_2_PRESET_SHIFT) & MTGV2_EVENT_PRESET_2_PRESET_MASK)
#define MTGV2_EVENT_PRESET_2_PRESET_GET(x) (((uint32_t)(x) & MTGV2_EVENT_PRESET_2_PRESET_MASK) >> MTGV2_EVENT_PRESET_2_PRESET_SHIFT)

/* Bitfield definition for register of struct array EVENT: PRESET_3 */
/*
 * PRESET (RW)
 *
 */
#define MTGV2_EVENT_PRESET_3_PRESET_MASK (0xFFFFFFFFUL)
#define MTGV2_EVENT_PRESET_3_PRESET_SHIFT (0U)
#define MTGV2_EVENT_PRESET_3_PRESET_SET(x) (((uint32_t)(x) << MTGV2_EVENT_PRESET_3_PRESET_SHIFT) & MTGV2_EVENT_PRESET_3_PRESET_MASK)
#define MTGV2_EVENT_PRESET_3_PRESET_GET(x) (((uint32_t)(x) & MTGV2_EVENT_PRESET_3_PRESET_MASK) >> MTGV2_EVENT_PRESET_3_PRESET_SHIFT)

/* Bitfield definition for register of struct array EVENT: TIMESTAMP */
/*
 * TIMESTAMP (RO)
 *
 */
#define MTGV2_EVENT_TIMESTAMP_TIMESTAMP_MASK (0xFFFFFFFFUL)
#define MTGV2_EVENT_TIMESTAMP_TIMESTAMP_SHIFT (0U)
#define MTGV2_EVENT_TIMESTAMP_TIMESTAMP_GET(x) (((uint32_t)(x) & MTGV2_EVENT_TIMESTAMP_TIMESTAMP_MASK) >> MTGV2_EVENT_TIMESTAMP_TIMESTAMP_SHIFT)

/* Bitfield definition for register: SW_EVENT */
/*
 * SW_EVENT_TRIG (RW)
 *
 */
#define MTGV2_SW_EVENT_SW_EVENT_TRIG_MASK (0x1U)
#define MTGV2_SW_EVENT_SW_EVENT_TRIG_SHIFT (0U)
#define MTGV2_SW_EVENT_SW_EVENT_TRIG_SET(x) (((uint32_t)(x) << MTGV2_SW_EVENT_SW_EVENT_TRIG_SHIFT) & MTGV2_SW_EVENT_SW_EVENT_TRIG_MASK)
#define MTGV2_SW_EVENT_SW_EVENT_TRIG_GET(x) (((uint32_t)(x) & MTGV2_SW_EVENT_SW_EVENT_TRIG_MASK) >> MTGV2_SW_EVENT_SW_EVENT_TRIG_SHIFT)

/* Bitfield definition for register: SW_GLB_RESET */
/*
 * SW_GLB_RESET (WO)
 *
 */
#define MTGV2_SW_GLB_RESET_SW_GLB_RESET_MASK (0x1U)
#define MTGV2_SW_GLB_RESET_SW_GLB_RESET_SHIFT (0U)
#define MTGV2_SW_GLB_RESET_SW_GLB_RESET_SET(x) (((uint32_t)(x) << MTGV2_SW_GLB_RESET_SW_GLB_RESET_SHIFT) & MTGV2_SW_GLB_RESET_SW_GLB_RESET_MASK)
#define MTGV2_SW_GLB_RESET_SW_GLB_RESET_GET(x) (((uint32_t)(x) & MTGV2_SW_GLB_RESET_SW_GLB_RESET_MASK) >> MTGV2_SW_GLB_RESET_SW_GLB_RESET_SHIFT)

/* Bitfield definition for register: IRQ_ENABLE */
/*
 * IRQ_ENABLE (RW)
 *
 */
#define MTGV2_IRQ_ENABLE_IRQ_ENABLE_MASK (0xFFFFFFFUL)
#define MTGV2_IRQ_ENABLE_IRQ_ENABLE_SHIFT (0U)
#define MTGV2_IRQ_ENABLE_IRQ_ENABLE_SET(x) (((uint32_t)(x) << MTGV2_IRQ_ENABLE_IRQ_ENABLE_SHIFT) & MTGV2_IRQ_ENABLE_IRQ_ENABLE_MASK)
#define MTGV2_IRQ_ENABLE_IRQ_ENABLE_GET(x) (((uint32_t)(x) & MTGV2_IRQ_ENABLE_IRQ_ENABLE_MASK) >> MTGV2_IRQ_ENABLE_IRQ_ENABLE_SHIFT)

/* Bitfield definition for register: IRQ_STATUS */
/*
 * IRQ_STATUS (W1C)
 *
 */
#define MTGV2_IRQ_STATUS_IRQ_STATUS_MASK (0xFFFFFFFUL)
#define MTGV2_IRQ_STATUS_IRQ_STATUS_SHIFT (0U)
#define MTGV2_IRQ_STATUS_IRQ_STATUS_SET(x) (((uint32_t)(x) << MTGV2_IRQ_STATUS_IRQ_STATUS_SHIFT) & MTGV2_IRQ_STATUS_IRQ_STATUS_MASK)
#define MTGV2_IRQ_STATUS_IRQ_STATUS_GET(x) (((uint32_t)(x) & MTGV2_IRQ_STATUS_IRQ_STATUS_MASK) >> MTGV2_IRQ_STATUS_IRQ_STATUS_SHIFT)

/* Bitfield definition for register: FILTER_CONTROL */
/*
 * ERR_INIT_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_ERR_INIT_EN_MASK (0x80000000UL)
#define MTGV2_FILTER_CONTROL_ERR_INIT_EN_SHIFT (31U)
#define MTGV2_FILTER_CONTROL_ERR_INIT_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_ERR_INIT_EN_SHIFT) & MTGV2_FILTER_CONTROL_ERR_INIT_EN_MASK)
#define MTGV2_FILTER_CONTROL_ERR_INIT_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ERR_INIT_EN_MASK) >> MTGV2_FILTER_CONTROL_ERR_INIT_EN_SHIFT)

/*
 * ERR_BYPASS_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_MASK (0x40000000UL)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_SHIFT (30U)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_SHIFT) & MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_MASK)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_MASK) >> MTGV2_FILTER_CONTROL_ERR_BYPASS_EN_SHIFT)

/*
 * ERR_BYPASS_MODE (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_MASK (0x20000000UL)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_SHIFT (29U)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_SHIFT) & MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_MASK)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_MASK) >> MTGV2_FILTER_CONTROL_ERR_BYPASS_MODE_SHIFT)

/*
 * ERR_BYPASS_I_F_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_MASK (0x10000000UL)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_SHIFT (28U)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_SHIFT) & MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_MASK)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_MASK) >> MTGV2_FILTER_CONTROL_ERR_BYPASS_I_F_EN_SHIFT)

/*
 * ERR_BYPASS_F_I_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_MASK (0x8000000UL)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_SHIFT (27U)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_SHIFT) & MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_MASK)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_MASK) >> MTGV2_FILTER_CONTROL_ERR_BYPASS_F_I_EN_SHIFT)

/*
 * ERR_BYPASS_STATUS (RO)
 *
 */
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_STATUS_MASK (0x4000000UL)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_STATUS_SHIFT (26U)
#define MTGV2_FILTER_CONTROL_ERR_BYPASS_STATUS_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ERR_BYPASS_STATUS_MASK) >> MTGV2_FILTER_CONTROL_ERR_BYPASS_STATUS_SHIFT)

/*
 * SW_LOCK (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_SW_LOCK_MASK (0x100000UL)
#define MTGV2_FILTER_CONTROL_SW_LOCK_SHIFT (20U)
#define MTGV2_FILTER_CONTROL_SW_LOCK_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_SW_LOCK_SHIFT) & MTGV2_FILTER_CONTROL_SW_LOCK_MASK)
#define MTGV2_FILTER_CONTROL_SW_LOCK_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_SW_LOCK_MASK) >> MTGV2_FILTER_CONTROL_SW_LOCK_SHIFT)

/*
 * TIMEOUT_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_TIMEOUT_EN_MASK (0x80000UL)
#define MTGV2_FILTER_CONTROL_TIMEOUT_EN_SHIFT (19U)
#define MTGV2_FILTER_CONTROL_TIMEOUT_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_TIMEOUT_EN_SHIFT) & MTGV2_FILTER_CONTROL_TIMEOUT_EN_MASK)
#define MTGV2_FILTER_CONTROL_TIMEOUT_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_TIMEOUT_EN_MASK) >> MTGV2_FILTER_CONTROL_TIMEOUT_EN_SHIFT)

/*
 * SEL_TIME1 (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_SEL_TIME1_MASK (0x3000U)
#define MTGV2_FILTER_CONTROL_SEL_TIME1_SHIFT (12U)
#define MTGV2_FILTER_CONTROL_SEL_TIME1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_SEL_TIME1_SHIFT) & MTGV2_FILTER_CONTROL_SEL_TIME1_MASK)
#define MTGV2_FILTER_CONTROL_SEL_TIME1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_SEL_TIME1_MASK) >> MTGV2_FILTER_CONTROL_SEL_TIME1_SHIFT)

/*
 * SEL_TIME0 (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_SEL_TIME0_MASK (0xC00U)
#define MTGV2_FILTER_CONTROL_SEL_TIME0_SHIFT (10U)
#define MTGV2_FILTER_CONTROL_SEL_TIME0_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_SEL_TIME0_SHIFT) & MTGV2_FILTER_CONTROL_SEL_TIME0_MASK)
#define MTGV2_FILTER_CONTROL_SEL_TIME0_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_SEL_TIME0_MASK) >> MTGV2_FILTER_CONTROL_SEL_TIME0_SHIFT)

/*
 * EN_TIME1 (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_EN_TIME1_MASK (0x200U)
#define MTGV2_FILTER_CONTROL_EN_TIME1_SHIFT (9U)
#define MTGV2_FILTER_CONTROL_EN_TIME1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_EN_TIME1_SHIFT) & MTGV2_FILTER_CONTROL_EN_TIME1_MASK)
#define MTGV2_FILTER_CONTROL_EN_TIME1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_EN_TIME1_MASK) >> MTGV2_FILTER_CONTROL_EN_TIME1_SHIFT)

/*
 * EN_TIME0 (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_EN_TIME0_MASK (0x100U)
#define MTGV2_FILTER_CONTROL_EN_TIME0_SHIFT (8U)
#define MTGV2_FILTER_CONTROL_EN_TIME0_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_EN_TIME0_SHIFT) & MTGV2_FILTER_CONTROL_EN_TIME0_MASK)
#define MTGV2_FILTER_CONTROL_EN_TIME0_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_EN_TIME0_MASK) >> MTGV2_FILTER_CONTROL_EN_TIME0_SHIFT)

/*
 * A_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_A_EN_MASK (0x40U)
#define MTGV2_FILTER_CONTROL_A_EN_SHIFT (6U)
#define MTGV2_FILTER_CONTROL_A_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_A_EN_SHIFT) & MTGV2_FILTER_CONTROL_A_EN_MASK)
#define MTGV2_FILTER_CONTROL_A_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_A_EN_MASK) >> MTGV2_FILTER_CONTROL_A_EN_SHIFT)

/*
 * FF_MODE (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_FF_MODE_MASK (0x8U)
#define MTGV2_FILTER_CONTROL_FF_MODE_SHIFT (3U)
#define MTGV2_FILTER_CONTROL_FF_MODE_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_FF_MODE_SHIFT) & MTGV2_FILTER_CONTROL_FF_MODE_MASK)
#define MTGV2_FILTER_CONTROL_FF_MODE_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_FF_MODE_MASK) >> MTGV2_FILTER_CONTROL_FF_MODE_SHIFT)

/*
 * FF_EN (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_FF_EN_MASK (0x4U)
#define MTGV2_FILTER_CONTROL_FF_EN_SHIFT (2U)
#define MTGV2_FILTER_CONTROL_FF_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_FF_EN_SHIFT) & MTGV2_FILTER_CONTROL_FF_EN_MASK)
#define MTGV2_FILTER_CONTROL_FF_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_FF_EN_MASK) >> MTGV2_FILTER_CONTROL_FF_EN_SHIFT)

/*
 * FIRST_LOAD_MODE (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_MASK (0x2U)
#define MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_SHIFT (1U)
#define MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_SHIFT) & MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_MASK)
#define MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_MASK) >> MTGV2_FILTER_CONTROL_FIRST_LOAD_MODE_SHIFT)

/*
 * ENABLE (RW)
 *
 */
#define MTGV2_FILTER_CONTROL_ENABLE_MASK (0x1U)
#define MTGV2_FILTER_CONTROL_ENABLE_SHIFT (0U)
#define MTGV2_FILTER_CONTROL_ENABLE_SET(x) (((uint32_t)(x) << MTGV2_FILTER_CONTROL_ENABLE_SHIFT) & MTGV2_FILTER_CONTROL_ENABLE_MASK)
#define MTGV2_FILTER_CONTROL_ENABLE_GET(x) (((uint32_t)(x) & MTGV2_FILTER_CONTROL_ENABLE_MASK) >> MTGV2_FILTER_CONTROL_ENABLE_SHIFT)

/* Bitfield definition for register: FILTER_VEL_FF */
/*
 * VALUE (RW)
 *
 */
#define MTGV2_FILTER_VEL_FF_VALUE_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_VEL_FF_VALUE_SHIFT (0U)
#define MTGV2_FILTER_VEL_FF_VALUE_SET(x) (((uint32_t)(x) << MTGV2_FILTER_VEL_FF_VALUE_SHIFT) & MTGV2_FILTER_VEL_FF_VALUE_MASK)
#define MTGV2_FILTER_VEL_FF_VALUE_GET(x) (((uint32_t)(x) & MTGV2_FILTER_VEL_FF_VALUE_MASK) >> MTGV2_FILTER_VEL_FF_VALUE_SHIFT)

/* Bitfield definition for register: FILTER_ACC_FF */
/*
 * VALUE (RW)
 *
 */
#define MTGV2_FILTER_ACC_FF_VALUE_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_ACC_FF_VALUE_SHIFT (0U)
#define MTGV2_FILTER_ACC_FF_VALUE_SET(x) (((uint32_t)(x) << MTGV2_FILTER_ACC_FF_VALUE_SHIFT) & MTGV2_FILTER_ACC_FF_VALUE_MASK)
#define MTGV2_FILTER_ACC_FF_VALUE_GET(x) (((uint32_t)(x) & MTGV2_FILTER_ACC_FF_VALUE_MASK) >> MTGV2_FILTER_ACC_FF_VALUE_SHIFT)

/* Bitfield definition for register: FILTER_TIME_CONSTANT_TP */
/*
 * TP (RW)
 *
 */
#define MTGV2_FILTER_TIME_CONSTANT_TP_TP_MASK (0xFFFFFFUL)
#define MTGV2_FILTER_TIME_CONSTANT_TP_TP_SHIFT (0U)
#define MTGV2_FILTER_TIME_CONSTANT_TP_TP_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_CONSTANT_TP_TP_SHIFT) & MTGV2_FILTER_TIME_CONSTANT_TP_TP_MASK)
#define MTGV2_FILTER_TIME_CONSTANT_TP_TP_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_CONSTANT_TP_TP_MASK) >> MTGV2_FILTER_TIME_CONSTANT_TP_TP_SHIFT)

/* Bitfield definition for register: FILTER_TIME_CONSTANT_TZ */
/*
 * TZ (RW)
 *
 */
#define MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_MASK (0xFFFFFFUL)
#define MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_SHIFT (0U)
#define MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_SHIFT) & MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_MASK)
#define MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_MASK) >> MTGV2_FILTER_TIME_CONSTANT_TZ_TZ_SHIFT)

/* Bitfield definition for register: FILTER_TIME_CONSTANT_TZ_1 */
/*
 * TZ_1 (RW)
 *
 */
#define MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_MASK (0xFFFFFFUL)
#define MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_SHIFT (0U)
#define MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_SHIFT) & MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_MASK)
#define MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_MASK) >> MTGV2_FILTER_TIME_CONSTANT_TZ_1_TZ_1_SHIFT)

/* Bitfield definition for register: FILTER_GAIN */
/*
 * GAIN_T0_EN (RW)
 *
 */
#define MTGV2_FILTER_GAIN_GAIN_T0_EN_MASK (0x80000000UL)
#define MTGV2_FILTER_GAIN_GAIN_T0_EN_SHIFT (31U)
#define MTGV2_FILTER_GAIN_GAIN_T0_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_GAIN_GAIN_T0_EN_SHIFT) & MTGV2_FILTER_GAIN_GAIN_T0_EN_MASK)
#define MTGV2_FILTER_GAIN_GAIN_T0_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_GAIN_GAIN_T0_EN_MASK) >> MTGV2_FILTER_GAIN_GAIN_T0_EN_SHIFT)

/*
 * GAIN_T1_EN (RW)
 *
 */
#define MTGV2_FILTER_GAIN_GAIN_T1_EN_MASK (0x40000000UL)
#define MTGV2_FILTER_GAIN_GAIN_T1_EN_SHIFT (30U)
#define MTGV2_FILTER_GAIN_GAIN_T1_EN_SET(x) (((uint32_t)(x) << MTGV2_FILTER_GAIN_GAIN_T1_EN_SHIFT) & MTGV2_FILTER_GAIN_GAIN_T1_EN_MASK)
#define MTGV2_FILTER_GAIN_GAIN_T1_EN_GET(x) (((uint32_t)(x) & MTGV2_FILTER_GAIN_GAIN_T1_EN_MASK) >> MTGV2_FILTER_GAIN_GAIN_T1_EN_SHIFT)

/*
 * K (RW)
 *
 */
#define MTGV2_FILTER_GAIN_K_MASK (0xFFFFFFUL)
#define MTGV2_FILTER_GAIN_K_SHIFT (0U)
#define MTGV2_FILTER_GAIN_K_SET(x) (((uint32_t)(x) << MTGV2_FILTER_GAIN_K_SHIFT) & MTGV2_FILTER_GAIN_K_MASK)
#define MTGV2_FILTER_GAIN_K_GET(x) (((uint32_t)(x) & MTGV2_FILTER_GAIN_K_MASK) >> MTGV2_FILTER_GAIN_K_SHIFT)

/* Bitfield definition for register: FILTER_STAGE_SHIFT0 */
/*
 * STAGE3_SHIFT1 (RW)
 *
 */
#define MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_MASK (0xF0000000UL)
#define MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_SHIFT (28U)
#define MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_SHIFT) & MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_MASK)
#define MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_MASK) >> MTGV2_FILTER_STAGE_SHIFT0_STAGE3_SHIFT1_SHIFT)

/* Bitfield definition for register: FILTER_STAGE_SHIFT1 */
/*
 * STAGE5_SHIFT1 (RW)
 *
 */
#define MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_MASK (0xF000U)
#define MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_SHIFT (12U)
#define MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_SHIFT) & MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_MASK)
#define MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_MASK) >> MTGV2_FILTER_STAGE_SHIFT1_STAGE5_SHIFT1_SHIFT)

/* Bitfield definition for register: FILTER_PARAM_SHIFT */
/*
 * ACC_SHIFT_PARAM (RW)
 *
 */
#define MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_MASK (0xF0000000UL)
#define MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_SHIFT (28U)
#define MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_SET(x) (((uint32_t)(x) << MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_SHIFT) & MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_MASK)
#define MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_GET(x) (((uint32_t)(x) & MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_MASK) >> MTGV2_FILTER_PARAM_SHIFT_ACC_SHIFT_PARAM_SHIFT)

/*
 * VEL_SHIFT_PARAM (RW)
 *
 */
#define MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_MASK (0xF000000UL)
#define MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_SHIFT (24U)
#define MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_SET(x) (((uint32_t)(x) << MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_SHIFT) & MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_MASK)
#define MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_GET(x) (((uint32_t)(x) & MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_MASK) >> MTGV2_FILTER_PARAM_SHIFT_VEL_SHIFT_PARAM_SHIFT)

/*
 * GAIN_K_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_MASK (0xF00000UL)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_SHIFT (20U)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_SHIFT) & MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_MASK)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_MASK) >> MTGV2_FILTER_PARAM_SHIFT_GAIN_K_SHIFT_SHIFT)

/*
 * GAIN_T0_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_MASK (0xF0000UL)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_SHIFT (16U)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_SHIFT) & MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_MASK)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_MASK) >> MTGV2_FILTER_PARAM_SHIFT_GAIN_T0_SHIFT_SHIFT)

/*
 * GAIN_T1_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_MASK (0xF000U)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_SHIFT (12U)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_SHIFT) & MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_MASK)
#define MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_MASK) >> MTGV2_FILTER_PARAM_SHIFT_GAIN_T1_SHIFT_SHIFT)

/* Bitfield definition for register: FILTER_TIME_SHIFT */
/*
 * ACC_SHIFT_TIME1 (RW)
 *
 */
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_MASK (0xF000U)
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_SHIFT (12U)
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_SHIFT) & MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_MASK)
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_MASK) >> MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME1_SHIFT)

/*
 * VEL_SHIFT_TIME1 (RW)
 *
 */
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_MASK (0xF00U)
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_SHIFT (8U)
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_SHIFT) & MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_MASK)
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_MASK) >> MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME1_SHIFT)

/*
 * ACC_SHIFT_TIME0 (RW)
 *
 */
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_MASK (0xF0U)
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_SHIFT (4U)
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_SHIFT) & MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_MASK)
#define MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_MASK) >> MTGV2_FILTER_TIME_SHIFT_ACC_SHIFT_TIME0_SHIFT)

/*
 * VEL_SHIFT_TIME0 (RW)
 *
 */
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_MASK (0xFU)
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_SHIFT (0U)
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_SHIFT) & MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_MASK)
#define MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_MASK) >> MTGV2_FILTER_TIME_SHIFT_VEL_SHIFT_TIME0_SHIFT)

/* Bitfield definition for register: FILTER_FF_SHIFT */
/*
 * OUTPUT_ACC_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_MASK (0xF000U)
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_SHIFT (12U)
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_SHIFT) & MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_MASK)
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_MASK) >> MTGV2_FILTER_FF_SHIFT_OUTPUT_ACC_SHIFT_SHIFT)

/*
 * FILTER_ACC_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_MASK (0xF00U)
#define MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_SHIFT (8U)
#define MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_SHIFT) & MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_MASK)
#define MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_MASK) >> MTGV2_FILTER_FF_SHIFT_FILTER_ACC_SHIFT_SHIFT)

/*
 * OUTPUT_VEL_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_MASK (0xF0U)
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_SHIFT (4U)
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_SHIFT) & MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_MASK)
#define MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_MASK) >> MTGV2_FILTER_FF_SHIFT_OUTPUT_VEL_SHIFT_SHIFT)

/*
 * FILTER_VEL_SHIFT (RW)
 *
 */
#define MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_MASK (0xFU)
#define MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_SHIFT (0U)
#define MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_SHIFT) & MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_MASK)
#define MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_MASK) >> MTGV2_FILTER_FF_SHIFT_FILTER_VEL_SHIFT_SHIFT)

/* Bitfield definition for register: FILTER_TIME1_SW_ADJUST */
/*
 * TIME (RW)
 *
 */
#define MTGV2_FILTER_TIME1_SW_ADJUST_TIME_MASK (0xFFFFFFUL)
#define MTGV2_FILTER_TIME1_SW_ADJUST_TIME_SHIFT (0U)
#define MTGV2_FILTER_TIME1_SW_ADJUST_TIME_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME1_SW_ADJUST_TIME_SHIFT) & MTGV2_FILTER_TIME1_SW_ADJUST_TIME_MASK)
#define MTGV2_FILTER_TIME1_SW_ADJUST_TIME_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME1_SW_ADJUST_TIME_MASK) >> MTGV2_FILTER_TIME1_SW_ADJUST_TIME_SHIFT)

/* Bitfield definition for register: FILTER_TIME0_SW_ADJUST */
/*
 * TIME (RW)
 *
 */
#define MTGV2_FILTER_TIME0_SW_ADJUST_TIME_MASK (0xFFFFFFUL)
#define MTGV2_FILTER_TIME0_SW_ADJUST_TIME_SHIFT (0U)
#define MTGV2_FILTER_TIME0_SW_ADJUST_TIME_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIME0_SW_ADJUST_TIME_SHIFT) & MTGV2_FILTER_TIME0_SW_ADJUST_TIME_MASK)
#define MTGV2_FILTER_TIME0_SW_ADJUST_TIME_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIME0_SW_ADJUST_TIME_MASK) >> MTGV2_FILTER_TIME0_SW_ADJUST_TIME_SHIFT)

/* Bitfield definition for register: FILTER_TIMEOUT_CNT */
/*
 * TIMEOUT_CNT (RW)
 *
 */
#define MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_SHIFT (0U)
#define MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_SET(x) (((uint32_t)(x) << MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_SHIFT) & MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_MASK)
#define MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_GET(x) (((uint32_t)(x) & MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_MASK) >> MTGV2_FILTER_TIMEOUT_CNT_TIMEOUT_CNT_SHIFT)

/* Bitfield definition for register: FILTER_REV_LOCK */
/*
 * REV_STATUS (RO)
 *
 */
#define MTGV2_FILTER_REV_LOCK_REV_STATUS_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_REV_LOCK_REV_STATUS_SHIFT (0U)
#define MTGV2_FILTER_REV_LOCK_REV_STATUS_GET(x) (((uint32_t)(x) & MTGV2_FILTER_REV_LOCK_REV_STATUS_MASK) >> MTGV2_FILTER_REV_LOCK_REV_STATUS_SHIFT)

/* Bitfield definition for register: FILTER_POS_LOCK */
/*
 * POS_STATUS (RO)
 *
 */
#define MTGV2_FILTER_POS_LOCK_POS_STATUS_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_POS_LOCK_POS_STATUS_SHIFT (0U)
#define MTGV2_FILTER_POS_LOCK_POS_STATUS_GET(x) (((uint32_t)(x) & MTGV2_FILTER_POS_LOCK_POS_STATUS_MASK) >> MTGV2_FILTER_POS_LOCK_POS_STATUS_SHIFT)

/* Bitfield definition for register: FILTER_VEL_LOCK */
/*
 * VEL_STATUS (RO)
 *
 */
#define MTGV2_FILTER_VEL_LOCK_VEL_STATUS_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_VEL_LOCK_VEL_STATUS_SHIFT (0U)
#define MTGV2_FILTER_VEL_LOCK_VEL_STATUS_GET(x) (((uint32_t)(x) & MTGV2_FILTER_VEL_LOCK_VEL_STATUS_MASK) >> MTGV2_FILTER_VEL_LOCK_VEL_STATUS_SHIFT)

/* Bitfield definition for register: FILTER_ACC_LOCK */
/*
 * ACC_STATUS (RO)
 *
 */
#define MTGV2_FILTER_ACC_LOCK_ACC_STATUS_MASK (0xFFFFFFFFUL)
#define MTGV2_FILTER_ACC_LOCK_ACC_STATUS_SHIFT (0U)
#define MTGV2_FILTER_ACC_LOCK_ACC_STATUS_GET(x) (((uint32_t)(x) & MTGV2_FILTER_ACC_LOCK_ACC_STATUS_MASK) >> MTGV2_FILTER_ACC_LOCK_ACC_STATUS_SHIFT)



/* CMD register group index macro definition */
#define MTGV2_CMD_0 (0UL)
#define MTGV2_CMD_1 (1UL)
#define MTGV2_CMD_2 (2UL)
#define MTGV2_CMD_3 (3UL)

/* TRA register group index macro definition */
#define MTGV2_TRA_0 (0UL)
#define MTGV2_TRA_1 (1UL)

/* EVENT register group index macro definition */
#define MTGV2_EVENT_0 (0UL)
#define MTGV2_EVENT_1 (1UL)
#define MTGV2_EVENT_2 (2UL)
#define MTGV2_EVENT_3 (3UL)


#endif /* HPM_MTGV2_H */
