/*
 * Copyright (c) 2024 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef ECAT_CONFIG_H
#define ECAT_CONFIG_H

#include "board.h"

/* Flash space allocation
* / ---------------- /
* /    APP           / 2M
* /------------------/
* / EEPROM emulation / 64K
* /------------------/
* /     FOE File     / 8K
* /------------------/
*/

#define FLASH_ADDR_BASE          BOARD_FLASH_BASE_ADDRESS
#define FLASH_SECTOR_SIZE        (0x1000U) /* 4096 */

/* Please allocate appropriate flash space for FLASH EEPROM to avoid conflicts with other flash content */
#define FLASH_EEPROM_ADDR        (0x200000) /* offset 2M */
#define FLASH_EEPROM_SIZE        (0x10000)

#define FLASH_FILE_ADDR          (FLASH_EEPROM_ADDR + FLASH_EEPROM_SIZE)
#define FLASH_FILE_SIZE          (0x2000 - 4) /* last 4 bytes for file size */

#define FLASH_FILE_SIZE_ADDR     (FLASH_FILE_ADDR + FLASH_FILE_SIZE)


/* ecat timer */
#define ECAT_TIMER_GPTMR        HPM_GPTMR0
#define ECAT_TIMER_GPTMR_CH     (0U)
#define ECAT_TIMER_GPTMR_CLK    (clock_gptmr0)
#define ECAT_TIMER_GPTRM_IRQ    IRQn_GPTMR0

/* ecat eeprom emulation function */
#define ECAT_EEPROM_FLASH_OFFSET      (FLASH_EEPROM_ADDR)
#define ECAT_EEPROM_FLASH_SECTOR_SIZE (FLASH_SECTOR_SIZE)
#define ECAT_EEPROM_FLASH_SECTOR_CNT  (FLASH_EEPROM_SIZE / FLASH_SECTOR_SIZE) /* suitable for 2K bytes eeprom space */
/* if a eeprom context generated by SSC, could use it to init EEPROM context in eeprom emulation function */
#define ECAT_INIT_EEPROM_CONTEXT_IN_PROGRAM (0)
/* EEPROM size in bytes, indicate the size of the actual connected eeprom */
#define ECAT_EEPROM_SIZE_BYTE         (16 * 1024)  /* 16K bytes = 128K bits */

/* ecat reset function */
#define ECAT_RESET_ESC_PERIPHERAL  0    /* ESC reset request will reset ethercat slave controller only, not suggest */
#define ECAT_RESET_ESC_WITH_MCU    1    /* ESC reset request will reset ethercat slave controller and mcu */


#endif /* ECAT_CONFIG_H */