/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */


#ifndef HPM_DMAMUX_H
#define HPM_DMAMUX_H

typedef struct {
    __W  uint32_t MUXCFG[64];                  /* 0x0 - 0xFC: HDMA0 MUX0 Configuration */
} DMAMUX_Type;


/* Bitfield definition for register array: MUXCFG */
/*
 * ENABLE (WO)
 *
 * DMA Mux Channel Enable
 * Enables the channel for DMA Mux. The DMA has separate channel enables/disables, which should be
 * used to disable or reconfigure a DMA channel.
 * 0b - DMA Mux channel is disabled
 * 1b - DMA Mux channel is enabled
 */
#define DMAMUX_MUXCFG_ENABLE_MASK (0x80000000UL)
#define DMAMUX_MUXCFG_ENABLE_SHIFT (31U)
#define DMAMUX_MUXCFG_ENABLE_SET(x) (((uint32_t)(x) << DMAMUX_MUXCFG_ENABLE_SHIFT) & DMAMUX_MUXCFG_ENABLE_MASK)
#define DMAMUX_MUXCFG_ENABLE_GET(x) (((uint32_t)(x) & DMAMUX_MUXCFG_ENABLE_MASK) >> DMAMUX_MUXCFG_ENABLE_SHIFT)

/*
 * SOURCE (WO)
 *
 * DMA Channel Source
 * Specifies which DMA source, if any, is routed to a particular DMA channel. See the "DMA MUX Mapping"
 */
#define DMAMUX_MUXCFG_SOURCE_MASK (0x7FU)
#define DMAMUX_MUXCFG_SOURCE_SHIFT (0U)
#define DMAMUX_MUXCFG_SOURCE_SET(x) (((uint32_t)(x) << DMAMUX_MUXCFG_SOURCE_SHIFT) & DMAMUX_MUXCFG_SOURCE_MASK)
#define DMAMUX_MUXCFG_SOURCE_GET(x) (((uint32_t)(x) & DMAMUX_MUXCFG_SOURCE_MASK) >> DMAMUX_MUXCFG_SOURCE_SHIFT)



/* MUXCFG register group index macro definition */
#define DMAMUX_MUXCFG_HDMA0_MUX0 (0UL)
#define DMAMUX_MUXCFG_HDMA0_MUX1 (1UL)
#define DMAMUX_MUXCFG_HDMA0_MUX2 (2UL)
#define DMAMUX_MUXCFG_HDMA0_MUX3 (3UL)
#define DMAMUX_MUXCFG_HDMA0_MUX4 (4UL)
#define DMAMUX_MUXCFG_HDMA0_MUX5 (5UL)
#define DMAMUX_MUXCFG_HDMA0_MUX6 (6UL)
#define DMAMUX_MUXCFG_HDMA0_MUX7 (7UL)
#define DMAMUX_MUXCFG_HDMA0_MUX8 (8UL)
#define DMAMUX_MUXCFG_HDMA0_MUX9 (9UL)
#define DMAMUX_MUXCFG_HDMA0_MUX10 (10UL)
#define DMAMUX_MUXCFG_HDMA0_MUX11 (11UL)
#define DMAMUX_MUXCFG_HDMA0_MUX12 (12UL)
#define DMAMUX_MUXCFG_HDMA0_MUX13 (13UL)
#define DMAMUX_MUXCFG_HDMA0_MUX14 (14UL)
#define DMAMUX_MUXCFG_HDMA0_MUX15 (15UL)
#define DMAMUX_MUXCFG_HDMA0_MUX16 (16UL)
#define DMAMUX_MUXCFG_HDMA0_MUX17 (17UL)
#define DMAMUX_MUXCFG_HDMA0_MUX18 (18UL)
#define DMAMUX_MUXCFG_HDMA0_MUX19 (19UL)
#define DMAMUX_MUXCFG_HDMA0_MUX20 (20UL)
#define DMAMUX_MUXCFG_HDMA0_MUX21 (21UL)
#define DMAMUX_MUXCFG_HDMA0_MUX22 (22UL)
#define DMAMUX_MUXCFG_HDMA0_MUX23 (23UL)
#define DMAMUX_MUXCFG_HDMA0_MUX24 (24UL)
#define DMAMUX_MUXCFG_HDMA0_MUX25 (25UL)
#define DMAMUX_MUXCFG_HDMA0_MUX26 (26UL)
#define DMAMUX_MUXCFG_HDMA0_MUX27 (27UL)
#define DMAMUX_MUXCFG_HDMA0_MUX28 (28UL)
#define DMAMUX_MUXCFG_HDMA0_MUX29 (29UL)
#define DMAMUX_MUXCFG_HDMA0_MUX30 (30UL)
#define DMAMUX_MUXCFG_HDMA0_MUX31 (31UL)
#define DMAMUX_MUXCFG_HDMA1_MUX0 (32UL)
#define DMAMUX_MUXCFG_HDMA1_MUX1 (33UL)
#define DMAMUX_MUXCFG_HDMA1_MUX2 (34UL)
#define DMAMUX_MUXCFG_HDMA1_MUX3 (35UL)
#define DMAMUX_MUXCFG_HDMA1_MUX4 (36UL)
#define DMAMUX_MUXCFG_HDMA1_MUX5 (37UL)
#define DMAMUX_MUXCFG_HDMA1_MUX6 (38UL)
#define DMAMUX_MUXCFG_HDMA1_MUX7 (39UL)
#define DMAMUX_MUXCFG_HDMA1_MUX8 (40UL)
#define DMAMUX_MUXCFG_HDMA1_MUX9 (41UL)
#define DMAMUX_MUXCFG_HDMA1_MUX10 (42UL)
#define DMAMUX_MUXCFG_HDMA1_MUX11 (43UL)
#define DMAMUX_MUXCFG_HDMA1_MUX12 (44UL)
#define DMAMUX_MUXCFG_HDMA1_MUX13 (45UL)
#define DMAMUX_MUXCFG_HDMA1_MUX14 (46UL)
#define DMAMUX_MUXCFG_HDMA1_MUX15 (47UL)
#define DMAMUX_MUXCFG_HDMA1_MUX16 (48UL)
#define DMAMUX_MUXCFG_HDMA1_MUX17 (49UL)
#define DMAMUX_MUXCFG_HDMA1_MUX18 (50UL)
#define DMAMUX_MUXCFG_HDMA1_MUX19 (51UL)
#define DMAMUX_MUXCFG_HDMA1_MUX20 (52UL)
#define DMAMUX_MUXCFG_HDMA1_MUX21 (53UL)
#define DMAMUX_MUXCFG_HDMA1_MUX22 (54UL)
#define DMAMUX_MUXCFG_HDMA1_MUX23 (55UL)
#define DMAMUX_MUXCFG_HDMA1_MUX24 (56UL)
#define DMAMUX_MUXCFG_HDMA1_MUX25 (57UL)
#define DMAMUX_MUXCFG_HDMA1_MUX26 (58UL)
#define DMAMUX_MUXCFG_HDMA1_MUX27 (59UL)
#define DMAMUX_MUXCFG_HDMA1_MUX28 (60UL)
#define DMAMUX_MUXCFG_HDMA1_MUX29 (61UL)
#define DMAMUX_MUXCFG_HDMA1_MUX30 (62UL)
#define DMAMUX_MUXCFG_HDMA1_MUX31 (63UL)


#endif /* HPM_DMAMUX_H */
