
/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_uart0_pins(void);
void init_uart4_pins(void);
void init_puart_pins(void);
void init_uart4_pin_as_gpio(void);
void init_i2c3_pins(void);
void init_i2c1_pins(void);
void init_femc_pins(void);
void init_ppi_pins(void);
void init_sdm_pins(void);
void init_pwm_pin_as_sdm_clock(void);
void init_gpio_pins(void);
void init_butn_pins(void);
void init_spi2_pins(void);
void init_spi2_pins_with_gpio_as_cs(void);
void init_gptmr0_pins(void);
void init_gptmr3_pins(void);
void init_acmp_pins(void);
void init_pwm_fault_pins(void);
void init_pwm1_pins(void);
void init_usb0_pins(void);
void init_clk_obs_pins(void);
void init_i2s0_pins(void);
void init_qeo1_pins(void);
void init_sei_ctrl1_pins(void);
void init_qeiv2_qei0_uvw_pins(void);
void init_qeiv2_qei0_ab_pins(void);
void init_qeiv2_qei0_abz_pins(void);
void init_rdc_pin(void);
void init_dao_pins(void);
void init_pdm_pins(void);
void init_enet0_pins(void);
void init_enet_pps_pins(void);
void init_enet_pps_capture_pins(void);
void init_adc16_pins(void);
void init_adc_bldc_pins(void);
void init_adc_qeiv2_pins(void);
void init_mcan1_pins(void);
void init_mcan1_transceiver_phy_pin(void);
void init_led_pins_as_gpio(void);
void init_led_pins_as_pwm(void);
void init_plb_pulse_pins(void);
void init_plb_ab_pins(void);
void init_plb_lin_pins(void);
void init_plb_filter_pins(void);
void init_uart_break_signal_pin(void);
void init_dac0_pins(void);
void init_dac1_pins(void);
void init_gptmr0_channel2_pin_as_output(void);
void init_gptmr3_channel0_pin_as_capture(void);
void init_gptmr3_channel0_pin_as_output(void);
void init_gptmr3_channel2_pin_as_output(void);
void init_brownout_indicate_pin(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
