
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#ifndef HPM_CLOCK_H
#define HPM_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

void init_board_clock(void);
void init_board_clock_source(void);
void init_display_system_clock(void);
void init_uart0_clock(void);
void init_uart1_clock(void);
void init_uart2_clock(void);
void init_uart3_clock(void);
void init_puart_clock(void);
void init_i2c0_clock(void);
void init_i2c1_clock(void);
void init_i2c2_clock(void);
void init_i2c3_clock(void);
void init_spi1_clock(void);
void init_spi2_clock(void);
void init_spi3_clock(void);
void init_can0_clock(void);
void init_can1_clock(void);
void init_can2_clock(void);
void init_can3_clock(void);
void init_can4_clock(void);
void init_can5_clock(void);
void init_can6_clock(void);
void init_can7_clock(void);
void init_camera0_clock(void);
void init_camera1_clock(void);
void init_adc0_bus_clock(void);
void init_adc0_analog_clock(void);
void init_gptmr0_clock(void);
void init_gptmr1_clock(void);
void init_gptmr2_clock(void);
void init_gptmr3_clock(void);
void init_gptmr4_clock(void);
void init_gptmr5_clock(void);
void init_gptmr6_clock(void);
void init_gptmr7_clock(void);
void init_ptmr_clock(void);
void init_gptmr0_clock_group1(void);
void init_gptmr1_clock_group1(void);
void init_gptmr2_clock_group1(void);
void init_gptmr3_clock_group1(void);
void init_gptmr4_clock_group1(void);
void init_gptmr5_clock_group1(void);
void init_gptmr6_clock_group1(void);
void init_gptmr7_clock_group1(void);
void init_ptmr_clock_group1(void);
void init_i2s0_clock_22050(void);
void init_i2s0_clock_default(void);
void init_i2s1_clock_22050(void);
void init_i2s1_clock_default(void);
void init_i2s3_clock_22050(void);
void init_i2s3_clock_default(void);
void init_dao_clock(void);
void init_pdm_clock(void);
void init_ddr2_800_clock(void);
void init_ddr3l_1333_clock(void);
void init_usb0_clock(void);
void init_ptp0_clock(void);
void init_ptp0_clock_group1(void);
void init_eth0_clock(void);
void init_eth0_clock_group1(void);
void init_gwc_clock(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_CLOCK_H */
