
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_ahb, 0);

    clock_add_to_group(clock_axic, 0);

    clock_add_to_group(clock_axis, 0);

    clock_add_to_group(clock_axiv, 0);

    clock_add_to_group(clock_axid, 0);

    clock_add_to_group(clock_axig, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_xdma, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_xram, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_ptpc, 0);
}

void init_board_clock_source(void)
{
    /* Generate pll0 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 600000000);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk0, pllctlv2_div_1p0);

    /* Generate clk_top_axis code */
    clock_set_source_divider(clock_axis, clk_src_pll1_clk0, 4);

    /* Generate clk_top_axig code */
    clock_set_source_divider(clock_axig, clk_src_pll1_clk0, 2);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}

void init_display_system_clock(void)
{
    clock_add_to_group(clock_gpu0, 0);

    clock_add_to_group(clock_gwc0, 0);

    clock_add_to_group(clock_gwc1, 0);

    clock_add_to_group(clock_lvb, 0);

    clock_add_to_group(clock_lcb, 0);

    clock_add_to_group(clock_lcd0, 0);

    clock_add_to_group(clock_dsi0, 0);

    clock_add_to_group(clock_dsi1, 0);

    clock_add_to_group(clock_camera0, 0);

    clock_add_to_group(clock_camera1, 0);

    clock_add_to_group(clock_jpeg, 0);

    clock_add_to_group(clock_pdma, 0);
}

void init_uart0_clock(void)
{
    clock_add_to_group(clock_uart0, 0);
}

void init_uart1_clock(void)
{
    clock_add_to_group(clock_uart1, 0);
}

void init_uart2_clock(void)
{
    clock_add_to_group(clock_uart2, 0);
}

void init_uart3_clock(void)
{
    clock_add_to_group(clock_uart3, 0);
}

void init_puart_clock(void)
{
    clock_add_to_group(clock_puart, 0);
}

void init_i2c0_clock(void)
{
    clock_add_to_group(clock_i2c0, 0);
}

void init_i2c1_clock(void)
{
    clock_add_to_group(clock_i2c1, 0);
}

void init_i2c2_clock(void)
{
    clock_add_to_group(clock_i2c2, 0);
}

void init_i2c3_clock(void)
{
    clock_add_to_group(clock_i2c3, 0);
}

void init_spi1_clock(void)
{
    clock_add_to_group(clock_spi1, 0);
}

void init_spi2_clock(void)
{
    clock_add_to_group(clock_spi2, 0);
}

void init_spi3_clock(void)
{
    clock_add_to_group(clock_spi3, 0);
}

void init_can0_clock(void)
{
    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can0, 0);
}

void init_can1_clock(void)
{
    /* Generate clk_top_can1 code */
    clock_set_source_divider(clock_can1, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can1, 0);
}

void init_can2_clock(void)
{
    /* Generate clk_top_can2 code */
    clock_set_source_divider(clock_can2, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can2, 0);
}

void init_can3_clock(void)
{
    /* Generate clk_top_can3 code */
    clock_set_source_divider(clock_can3, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can3, 0);
}

void init_can4_clock(void)
{
    /* Generate clk_top_can4 code */
    clock_set_source_divider(clock_can4, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can4, 0);
}

void init_can5_clock(void)
{
    /* Generate clk_top_can5 code */
    clock_set_source_divider(clock_can5, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can5, 0);
}

void init_can6_clock(void)
{
    /* Generate clk_top_can6 code */
    clock_set_source_divider(clock_can6, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can6, 0);
}

void init_can7_clock(void)
{
    /* Generate clk_top_can7 code */
    clock_set_source_divider(clock_can7, clk_src_pll1_clk0, 10);

    clock_add_to_group(clock_can7, 0);
}

void init_camera0_clock(void)
{
    /* Generate clk_top_cam0 code */
    clock_set_source_divider(clock_camera0, clk_src_osc24m, 1);

    clock_add_to_group(clock_camera0, 0);
}

void init_camera1_clock(void)
{
    /* Generate clk_top_cam1 code */
    clock_set_source_divider(clock_camera1, clk_src_osc24m, 1);

    clock_add_to_group(clock_camera1, 0);
}

void init_adc0_bus_clock(void)
{
    /* Generate clk_top_adc0 code */
    clock_set_adc_source(clock_adc0, clk_adc_src_axi0);
    clock_set_source_divider(clock_axis, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc0, 0);
}

void init_adc0_analog_clock(void)
{
    /*
     * Generate clk_top_adc0 code
     * Generate clk_top_ana0 code
     */
    clock_set_adc_source(clock_adc0, clk_adc_src_ana0);
    clock_set_source_divider(clock_ana0, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_adc0, 0);
}

void init_gptmr0_clock(void)
{
    clock_add_to_group(clock_gptmr0, 0);
}

void init_gptmr1_clock(void)
{
    clock_add_to_group(clock_gptmr1, 0);
}

void init_gptmr2_clock(void)
{
    clock_add_to_group(clock_gptmr2, 0);
}

void init_gptmr3_clock(void)
{
    clock_add_to_group(clock_gptmr3, 0);
}

void init_gptmr4_clock(void)
{
    clock_add_to_group(clock_gptmr4, 0);
}

void init_gptmr5_clock(void)
{
    clock_add_to_group(clock_gptmr5, 0);
}

void init_gptmr6_clock(void)
{
    clock_add_to_group(clock_gptmr6, 0);
}

void init_gptmr7_clock(void)
{
    clock_add_to_group(clock_gptmr7, 0);
}

void init_ptmr_clock(void)
{
    clock_add_to_group(clock_ptmr, 0);
}

void init_gptmr0_clock_group1(void)
{
    clock_add_to_group(clock_gptmr0, 1);
}

void init_gptmr1_clock_group1(void)
{
    clock_add_to_group(clock_gptmr1, 1);
}

void init_gptmr2_clock_group1(void)
{
    clock_add_to_group(clock_gptmr2, 1);
}

void init_gptmr3_clock_group1(void)
{
    clock_add_to_group(clock_gptmr3, 1);
}

void init_gptmr4_clock_group1(void)
{
    clock_add_to_group(clock_gptmr4, 1);
}

void init_gptmr5_clock_group1(void)
{
    clock_add_to_group(clock_gptmr5, 1);
}

void init_gptmr6_clock_group1(void)
{
    clock_add_to_group(clock_gptmr6, 1);
}

void init_gptmr7_clock_group1(void)
{
    clock_add_to_group(clock_gptmr7, 1);
}

void init_ptmr_clock_group1(void)
{
    clock_add_to_group(clock_ptmr, 1);
}

void init_i2s0_clock_22050(void)
{
    /* Generate clk_top_i2s0 code */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll1_clk0, 71);

    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s0_clock_default(void)
{
    /* Generate clk_top_i2s0 code */
    clock_set_i2s_source(clock_i2s0, clk_i2s_src_aud0);
    clock_set_source_divider(clock_aud0, clk_src_pll3_clk0, 21);

    clock_add_to_group(clock_i2s0, 0);
}

void init_i2s1_clock_22050(void)
{
    /* Generate clk_top_i2s1 code */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll1_clk0, 71);

    clock_add_to_group(clock_i2s1, 0);
}

void init_i2s1_clock_default(void)
{
    /* Generate clk_top_i2s1 code */
    clock_set_i2s_source(clock_i2s1, clk_i2s_src_aud1);
    clock_set_source_divider(clock_aud1, clk_src_pll3_clk0, 21);

    clock_add_to_group(clock_i2s1, 0);
}

void init_i2s3_clock_22050(void)
{
    /* Generate clk_top_i2s3 code */
    clock_set_i2s_source(clock_i2s3, clk_i2s_src_aud3);
    clock_set_source_divider(clock_aud3, clk_src_pll1_clk0, 71);

    clock_add_to_group(clock_i2s3, 0);
}

void init_i2s3_clock_default(void)
{
    /* Generate clk_top_i2s3 code */
    clock_set_i2s_source(clock_i2s3, clk_i2s_src_aud3);
    clock_set_source_divider(clock_aud3, clk_src_pll3_clk0, 21);

    clock_add_to_group(clock_i2s3, 0);
}

void init_dao_clock(void)
{
    clock_add_to_group(clock_dao, 0);
}

void init_pdm_clock(void)
{
    clock_add_to_group(clock_pdm, 0);
}

void init_ddr2_800_clock(void)
{
    /* Generate clk_top_axif code */
    clock_set_source_divider(clock_axif, clk_src_pll1_clk0, 4);

    clock_add_to_group(clock_ddr0, 0);
}

void init_ddr3l_1333_clock(void)
{
    /* Generate clk_top_axif code */
    clock_set_source_divider(clock_axif, clk_src_pll1_clk1, 2);

    clock_add_to_group(clock_ddr0, 0);
}

void init_usb0_clock(void)
{
    clock_add_to_group(clock_usb0, 0);
}

void init_ptp0_clock(void)
{
    /* Generate clk_top_ptp0 code */
    clock_set_source_divider(clock_ptp0, clk_src_pll1_clk0, 8);

    clock_add_to_group(clock_ptp0, 0);
}

void init_ptp0_clock_group1(void)
{
    /* Generate clk_top_ptp0 code */
    clock_set_source_divider(clock_ptp0, clk_src_pll1_clk0, 8);

    clock_add_to_group(clock_ptp0, 1);
}

void init_eth0_clock(void)
{
    clock_add_to_group(clock_eth0, 0);
}

void init_eth0_clock_group1(void)
{
    clock_add_to_group(clock_eth0, 1);
}

void init_gwc_clock(void)
{
    clock_add_to_group(clock_gwc0, 0);

    clock_add_to_group(clock_gwc1, 0);

    clock_add_to_group(clock_lcd0, 0);

    clock_add_to_group(clock_crc0, 0);
}
