
/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_uart0_pins(void);
void init_uart3_pins(void);
void init_puart_pins(void);
void init_uart3_pin_as_gpio(void);
void init_cap_pins(void);
void init_i2c3_pins(void);
void init_i2c1_pins(void);
void init_i2c0_pins(void);
void init_cam_pins(void);
void init_cam_mipi_csi_pins(void);
void init_sdm_pins(void);
void init_gpio_pins(void);
void init_spi3_pins(void);
void init_spi3_pins_with_gpio_as_cs(void);
void init_gptmr2_pins(void);
void init_butn_pins(void);
void init_acmp_pins(void);
void init_sdxc0_cmd_pin_enable_opendrain(void);
void init_sdxc0_cmd_pin_disable_opendrain(void);
void init_sdxc1_cmd_pin(void);
void init_sdxc0_ds_pin(void);
void init_sdxc1_pwr_pin(void);
void init_sdxc1_vsel_pin(void);
void init_sdxc1_cd_pin(void);
void init_sdxc0_clk_data_pins(void);
void init_sdxc0_clk_data_pins_width4(void);
void init_sdxc0_clk_data_pins_width8(void);
void init_sdxc1_clk_data_pins(void);
void init_usb0_pins(void);
void init_mcan3_pins(void);
void init_mcan3_transceiver_phy_pin(void);
void init_clk_obs_pins(void);
void init_led_pins_as_gpio(void);
void init_mipi_lvds_tx_phy0_pin(void);
void init_mipi_lvds_tx_phy1_pin(void);
void init_mipi_lvds_rx_phy0_pin(void);
void init_mipi_lvds_rx_phy1_pin(void);
void init_lcd_mipi_ctl_pins(void);
void init_lcd_lvds_double_ctl_pins(void);
void init_lcd_lvds_single_ctl_pins(void);
void init_lcd_rgb_ctl_pins(void);
void init_lcd_rgb_pins(void);
void init_i2s3_pins(void);
void init_dao_pins(void);
void init_pdm_pins(void);
void init_enet0_pins(void);
void init_enet_pps_pins(void);
void init_enet_pps_capture_pins(void);
void init_adc_pins(void);
void init_tamper_pins(void);
void init_uart_break_signal_pin(void);
void init_gptmr2_channel0_pin_as_output(void);
void init_gptmr2_channel1_pin_as_output(void);
void init_gptmr2_channel2_pin_as_output(void);
void init_gptmr2_channel0_pin_as_capture(void);
void init_clk_ref_pin(void);
void init_brownout_indicate_pin(void);
void board_init_i2c_eeprom_pin(void);
void board_init_spi_eeprom_pin(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
